services:
  postgres:
    image: postgres:latest
    container_name: wealth_and_vault
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: wealthvault
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_wealth
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: always
    depends_on:
      - postgres

  nats-server:
    image: nats:2.10
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js"]

  user-service:
    build:
      context: ./services/user-service  
      dockerfile: dockerfile 
    container_name: user-service
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./services/user-service/.user.env
    ports:
      - "50051:50051"

  auth-service:
    build:
      context: ./services/auth-service  
      dockerfile: dockerfile 
    container_name: auth-service
    restart: always
    depends_on:
      - nats-server
      - postgres
    env_file:
      - ./services/auth-service/.auth.env
    ports:
      - "50052:50052"

  asset-service:
    build:
      context: ./services/asset-service  
      dockerfile: dockerfile 
    container_name: asset-service
    restart: always
    depends_on:
      - postgres
    env_file:
      - ./services/asset-service/.asset.env
    ports:
      - "50053:50053"

  notification-service:
    build:
      context: ./services/notification-service  
      dockerfile: dockerfile 
    container_name: notification-service
    restart: always
    depends_on:
      - nats-server
      - postgres
    env_file:
      - ./services/notification-service/.noti.env
    ports:
      - "50054:50054"

  api-gateway:
    build:
      context: ./api-gateway              
      dockerfile: dockerfile
    container_name: api-gateway
    restart: always
    depends_on:
      - notification-service
      - user-service
      - auth-service
      - asset-service
    env_file:
      - ./api-gateway/.env
    ports:
      - "8080:8080"

volumes:
  postgres_data: