CREATE DATABASE user_db;
GRANT ALL PRIVILEGES ON DATABASE user_db TO admin;
CREATE DATABASE auth_db;
GRANT ALL PRIVILEGES ON DATABASE auth_db TO admin;
CREATE DATABASE asset_db;
GRANT ALL PRIVILEGES ON DATABASE asset_db TO admin;
CREATE DATABASE noti_db;
GRANT ALL PRIVILEGES ON DATABASE noti_db TO admin;