syntax = "proto3";

package asset;

option go_package = "wealth-vault/pkg/pb";

import "google/protobuf/timestamp.proto";

// ------Request/Response------
message GetAssetRequest {
  string user_id = 1; 
}

message GetAssetByIDRequest {
  string id = 1;
  string user_id = 2;
}

message GetBatchIdsRequest {
  repeated string ids = 1;
}

message GetNetWorthRequest { 
  string user_id = 1; 
}

message GetNetWorthResponse { 
  int64 item_count = 1;
  double assets_value = 2; 
  double liabilities_value = 3; 
  double net_worth = 4; 
}

message DeleteAssetRequest {
  string id = 1;
  string user_id = 2;
}

message DeleteAssetResponse {
  bool success = 1;
}

message CheckAssetRequest {
  string id = 1;
  string user_id = 2;
  string type = 3;
}

message CheckAssetResponse {
  bool exists = 1;
  string name = 2;
}

message GetMyAssetsRequest {
  string user_id = 1;
}

message GetMyAssetsResponse {
  repeated string account_ids = 1;
  repeated string building_ids = 2;
  repeated string cash_ids = 3;
  repeated string insurance_ids = 4;
  repeated string investment_ids = 5;
  repeated string land_ids = 6;
  repeated string liability_ids = 7;
}

message AssetSummary {
  string id = 1;
  string type = 2;
  string name = 3;
  double value = 4;
  string image = 5;
  google.protobuf.Timestamp created_at = 6;
}

message GetAllAssetsRequest {
  string user_id = 1; 
}

message GetAllAssetsResponse {
  repeated AssetSummary assets = 1;
  repeated AssetSummary liabilities = 2;
}