syntax = "proto3";

package asset;

option go_package = "wealth-vault/pkg/pb";

// ------Request/Response------
message GetAssetRequest {
  string user_id = 1; 
}

message GetAssetByIDRequest {
  string id = 1;
  string user_id = 2;
}

message GetBatchIdsRequest {
  repeated string ids = 1;
}

message GetNetWorthRequest { 
  string user_id = 1; 
}

message GetNetWorthResponse { 
    double total_assets = 1; 
    double total_liabilities = 2; 
    double net_worth = 3; 
}

message DeleteAssetRequest {
  string id = 1;
  string user_id = 2;
}

message DeleteAssetResponse {
  bool success = 1;
}

message CheckAssetRequest {
  string id = 1;
  string user_id = 2;
  string type = 3;
}

message CheckAssetResponse {
  bool exists = 1;
}