syntax = "proto3";

package asset;

option go_package = "wealth-vault/pkg/pb";

import "google/protobuf/timestamp.proto";
import "google/protobuf/field_mask.proto";

// ------Model------
message Cash {
  string id = 1;
  string name = 2;
  double amount = 3;
  string description = 4;
  string created_by = 5;
  google.protobuf.Timestamp created_at = 6;
  google.protobuf.Timestamp updated_at = 7;
}

// ------Request------
message CreateCashRequest {
  string name = 1;
  double amount = 2;
  string description = 3;
  string created_by = 4;
}

message GetCashRequest {
  string user_id = 1;
}

message GetCashByIDRequest {
  string user_id = 1;
  string id = 2;
}

message UpdateCashRequest {
  string id = 1;          
  Cash cash = 2;
  google.protobuf.FieldMask update_mask = 3;  
}

// ------Response------
message CreateCashResponse {
  bool success = 1;
  string cash_id = 2;
}

message CashArrayResponse {
  bool success = 1;
  repeated Cash cash = 2;
}

message CashResponse {
  bool success = 1;
  Cash cash = 2;
}