// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/user/share.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShareTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ShareAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=share_at,json=shareAt,proto3" json:"share_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareTarget) Reset() {
	*x = ShareTarget{}
	mi := &file_proto_user_share_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareTarget) ProtoMessage() {}

func (x *ShareTarget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareTarget.ProtoReflect.Descriptor instead.
func (*ShareTarget) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{0}
}

func (x *ShareTarget) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShareTarget) GetShareAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ShareAt
	}
	return nil
}

type ShareItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemIds       []string               `protobuf:"bytes,2,rep,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	ItemTypes     []string               `protobuf:"bytes,3,rep,name=item_types,json=itemTypes,proto3" json:"item_types,omitempty"`
	Groups        []*ShareTarget         `protobuf:"bytes,4,rep,name=groups,proto3" json:"groups,omitempty"`
	Friends       []*ShareTarget         `protobuf:"bytes,5,rep,name=friends,proto3" json:"friends,omitempty"`
	Emails        []*ShareTarget         `protobuf:"bytes,6,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareItemRequest) Reset() {
	*x = ShareItemRequest{}
	mi := &file_proto_user_share_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareItemRequest) ProtoMessage() {}

func (x *ShareItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareItemRequest.ProtoReflect.Descriptor instead.
func (*ShareItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{1}
}

func (x *ShareItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShareItemRequest) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

func (x *ShareItemRequest) GetItemTypes() []string {
	if x != nil {
		return x.ItemTypes
	}
	return nil
}

func (x *ShareItemRequest) GetGroups() []*ShareTarget {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ShareItemRequest) GetFriends() []*ShareTarget {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *ShareItemRequest) GetEmails() []*ShareTarget {
	if x != nil {
		return x.Emails
	}
	return nil
}

type ShareItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Finish        bool                   `protobuf:"varint,1,opt,name=finish,proto3" json:"finish,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShareItemResponse) Reset() {
	*x = ShareItemResponse{}
	mi := &file_proto_user_share_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShareItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareItemResponse) ProtoMessage() {}

func (x *ShareItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareItemResponse.ProtoReflect.Descriptor instead.
func (*ShareItemResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{2}
}

func (x *ShareItemResponse) GetFinish() bool {
	if x != nil {
		return x.Finish
	}
	return false
}

type GetGroupItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupItemsRequest) Reset() {
	*x = GetGroupItemsRequest{}
	mi := &file_proto_user_share_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupItemsRequest) ProtoMessage() {}

func (x *GetGroupItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupItemsRequest.ProtoReflect.Descriptor instead.
func (*GetGroupItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{3}
}

func (x *GetGroupItemsRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetGroupItemsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFriendItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      string                 `protobuf:"bytes,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendItemRequest) Reset() {
	*x = GetFriendItemRequest{}
	mi := &file_proto_user_share_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendItemRequest) ProtoMessage() {}

func (x *GetFriendItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendItemRequest.ProtoReflect.Descriptor instead.
func (*GetFriendItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{4}
}

func (x *GetFriendItemRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *GetFriendItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetGroupItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*GroupItemDetail     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupItemsResponse) Reset() {
	*x = GetGroupItemsResponse{}
	mi := &file_proto_user_share_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupItemsResponse) ProtoMessage() {}

func (x *GetGroupItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupItemsResponse.ProtoReflect.Descriptor instead.
func (*GetGroupItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{5}
}

func (x *GetGroupItemsResponse) GetItems() []*GroupItemDetail {
	if x != nil {
		return x.Items
	}
	return nil
}

type GroupItemDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupItemId   string                 `protobuf:"bytes,1,opt,name=group_item_id,json=groupItemId,proto3" json:"group_item_id,omitempty"`
	SharedBy      string                 `protobuf:"bytes,2,opt,name=shared_by,json=sharedBy,proto3" json:"shared_by,omitempty"`
	SharedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=shared_at,json=sharedAt,proto3" json:"shared_at,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	AssetDetail   *AssetPreview          `protobuf:"bytes,5,opt,name=asset_detail,json=assetDetail,proto3" json:"asset_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupItemDetail) Reset() {
	*x = GroupItemDetail{}
	mi := &file_proto_user_share_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupItemDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupItemDetail) ProtoMessage() {}

func (x *GroupItemDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupItemDetail.ProtoReflect.Descriptor instead.
func (*GroupItemDetail) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{6}
}

func (x *GroupItemDetail) GetGroupItemId() string {
	if x != nil {
		return x.GroupItemId
	}
	return ""
}

func (x *GroupItemDetail) GetSharedBy() string {
	if x != nil {
		return x.SharedBy
	}
	return ""
}

func (x *GroupItemDetail) GetSharedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SharedAt
	}
	return nil
}

func (x *GroupItemDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GroupItemDetail) GetAssetDetail() *AssetPreview {
	if x != nil {
		return x.AssetDetail
	}
	return nil
}

type GetFriendItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FriendItemDetail    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFriendItemsResponse) Reset() {
	*x = GetFriendItemsResponse{}
	mi := &file_proto_user_share_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFriendItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFriendItemsResponse) ProtoMessage() {}

func (x *GetFriendItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFriendItemsResponse.ProtoReflect.Descriptor instead.
func (*GetFriendItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{7}
}

func (x *GetFriendItemsResponse) GetItems() []*FriendItemDetail {
	if x != nil {
		return x.Items
	}
	return nil
}

type FriendItemDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendItemId  string                 `protobuf:"bytes,1,opt,name=friend_item_id,json=friendItemId,proto3" json:"friend_item_id,omitempty"`
	SharedBy      string                 `protobuf:"bytes,2,opt,name=shared_by,json=sharedBy,proto3" json:"shared_by,omitempty"`
	SharedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=shared_at,json=sharedAt,proto3" json:"shared_at,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	AssetDetail   *AssetPreview          `protobuf:"bytes,5,opt,name=asset_detail,json=assetDetail,proto3" json:"asset_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendItemDetail) Reset() {
	*x = FriendItemDetail{}
	mi := &file_proto_user_share_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendItemDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendItemDetail) ProtoMessage() {}

func (x *FriendItemDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendItemDetail.ProtoReflect.Descriptor instead.
func (*FriendItemDetail) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{8}
}

func (x *FriendItemDetail) GetFriendItemId() string {
	if x != nil {
		return x.FriendItemId
	}
	return ""
}

func (x *FriendItemDetail) GetSharedBy() string {
	if x != nil {
		return x.SharedBy
	}
	return ""
}

func (x *FriendItemDetail) GetSharedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SharedAt
	}
	return nil
}

func (x *FriendItemDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FriendItemDetail) GetAssetDetail() *AssetPreview {
	if x != nil {
		return x.AssetDetail
	}
	return nil
}

type UnshareItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnshareItemRequest) Reset() {
	*x = UnshareItemRequest{}
	mi := &file_proto_user_share_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnshareItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnshareItemRequest) ProtoMessage() {}

func (x *UnshareItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnshareItemRequest.ProtoReflect.Descriptor instead.
func (*UnshareItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{9}
}

func (x *UnshareItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *UnshareItemRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteByEntityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByEntityRequest) Reset() {
	*x = DeleteByEntityRequest{}
	mi := &file_proto_user_share_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByEntityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByEntityRequest) ProtoMessage() {}

func (x *DeleteByEntityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByEntityRequest.ProtoReflect.Descriptor instead.
func (*DeleteByEntityRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteByEntityRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

type DeleteByEntityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteByEntityResponse) Reset() {
	*x = DeleteByEntityResponse{}
	mi := &file_proto_user_share_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteByEntityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteByEntityResponse) ProtoMessage() {}

func (x *DeleteByEntityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteByEntityResponse.ProtoReflect.Descriptor instead.
func (*DeleteByEntityResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteByEntityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetItemSharedTargetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemType      string                 `protobuf:"bytes,3,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemSharedTargetsRequest) Reset() {
	*x = GetItemSharedTargetsRequest{}
	mi := &file_proto_user_share_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemSharedTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemSharedTargetsRequest) ProtoMessage() {}

func (x *GetItemSharedTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemSharedTargetsRequest.ProtoReflect.Descriptor instead.
func (*GetItemSharedTargetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{12}
}

func (x *GetItemSharedTargetsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetItemSharedTargetsRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GetItemSharedTargetsRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

type SharedGroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	GroupImage    string                 `protobuf:"bytes,3,opt,name=group_image,json=groupImage,proto3" json:"group_image,omitempty"`
	MemberCount   int64                  `protobuf:"varint,4,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	SharedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=shared_at,json=sharedAt,proto3" json:"shared_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedGroupInfo) Reset() {
	*x = SharedGroupInfo{}
	mi := &file_proto_user_share_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedGroupInfo) ProtoMessage() {}

func (x *SharedGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedGroupInfo.ProtoReflect.Descriptor instead.
func (*SharedGroupInfo) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{13}
}

func (x *SharedGroupInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *SharedGroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *SharedGroupInfo) GetGroupImage() string {
	if x != nil {
		return x.GroupImage
	}
	return ""
}

func (x *SharedGroupInfo) GetMemberCount() int64 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *SharedGroupInfo) GetSharedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SharedAt
	}
	return nil
}

type SharedFriendInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FriendId      string                 `protobuf:"bytes,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	ProfileImage  string                 `protobuf:"bytes,3,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	SharedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=shared_at,json=sharedAt,proto3" json:"shared_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedFriendInfo) Reset() {
	*x = SharedFriendInfo{}
	mi := &file_proto_user_share_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedFriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedFriendInfo) ProtoMessage() {}

func (x *SharedFriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedFriendInfo.ProtoReflect.Descriptor instead.
func (*SharedFriendInfo) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{14}
}

func (x *SharedFriendInfo) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

func (x *SharedFriendInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SharedFriendInfo) GetProfileImage() string {
	if x != nil {
		return x.ProfileImage
	}
	return ""
}

func (x *SharedFriendInfo) GetSharedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SharedAt
	}
	return nil
}

type SharedEmailInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	SharedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=shared_at,json=sharedAt,proto3" json:"shared_at,omitempty"`
	IsSent        bool                   `protobuf:"varint,3,opt,name=is_sent,json=isSent,proto3" json:"is_sent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedEmailInfo) Reset() {
	*x = SharedEmailInfo{}
	mi := &file_proto_user_share_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedEmailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedEmailInfo) ProtoMessage() {}

func (x *SharedEmailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedEmailInfo.ProtoReflect.Descriptor instead.
func (*SharedEmailInfo) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{15}
}

func (x *SharedEmailInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SharedEmailInfo) GetSharedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SharedAt
	}
	return nil
}

func (x *SharedEmailInfo) GetIsSent() bool {
	if x != nil {
		return x.IsSent
	}
	return false
}

type GetItemSharedTargetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*SharedGroupInfo     `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Friends       []*SharedFriendInfo    `protobuf:"bytes,2,rep,name=friends,proto3" json:"friends,omitempty"`
	Emails        []*SharedEmailInfo     `protobuf:"bytes,3,rep,name=emails,proto3" json:"emails,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemSharedTargetsResponse) Reset() {
	*x = GetItemSharedTargetsResponse{}
	mi := &file_proto_user_share_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemSharedTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemSharedTargetsResponse) ProtoMessage() {}

func (x *GetItemSharedTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemSharedTargetsResponse.ProtoReflect.Descriptor instead.
func (*GetItemSharedTargetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{16}
}

func (x *GetItemSharedTargetsResponse) GetGroups() []*SharedGroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GetItemSharedTargetsResponse) GetFriends() []*SharedFriendInfo {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *GetItemSharedTargetsResponse) GetEmails() []*SharedEmailInfo {
	if x != nil {
		return x.Emails
	}
	return nil
}

type GetSharedItemIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	TargetType    string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSharedItemIDsRequest) Reset() {
	*x = GetSharedItemIDsRequest{}
	mi := &file_proto_user_share_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSharedItemIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSharedItemIDsRequest) ProtoMessage() {}

func (x *GetSharedItemIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSharedItemIDsRequest.ProtoReflect.Descriptor instead.
func (*GetSharedItemIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{17}
}

func (x *GetSharedItemIDsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetSharedItemIDsRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *GetSharedItemIDsRequest) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

type GetSharedItemIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemIds       []string               `protobuf:"bytes,1,rep,name=item_ids,json=itemIds,proto3" json:"item_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSharedItemIDsResponse) Reset() {
	*x = GetSharedItemIDsResponse{}
	mi := &file_proto_user_share_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSharedItemIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSharedItemIDsResponse) ProtoMessage() {}

func (x *GetSharedItemIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSharedItemIDsResponse.ProtoReflect.Descriptor instead.
func (*GetSharedItemIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{18}
}

func (x *GetSharedItemIDsResponse) GetItemIds() []string {
	if x != nil {
		return x.ItemIds
	}
	return nil
}

type GetItemsSharedByFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      string                 `protobuf:"bytes,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsSharedByFriendRequest) Reset() {
	*x = GetItemsSharedByFriendRequest{}
	mi := &file_proto_user_share_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsSharedByFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsSharedByFriendRequest) ProtoMessage() {}

func (x *GetItemsSharedByFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsSharedByFriendRequest.ProtoReflect.Descriptor instead.
func (*GetItemsSharedByFriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{19}
}

func (x *GetItemsSharedByFriendRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetItemsSharedByFriendRequest) GetFriendId() string {
	if x != nil {
		return x.FriendId
	}
	return ""
}

type SharedAssetPreview struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	AssetDetail   *AssetPreview          `protobuf:"bytes,3,opt,name=asset_detail,json=assetDetail,proto3" json:"asset_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SharedAssetPreview) Reset() {
	*x = SharedAssetPreview{}
	mi := &file_proto_user_share_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SharedAssetPreview) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SharedAssetPreview) ProtoMessage() {}

func (x *SharedAssetPreview) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SharedAssetPreview.ProtoReflect.Descriptor instead.
func (*SharedAssetPreview) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{20}
}

func (x *SharedAssetPreview) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SharedAssetPreview) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SharedAssetPreview) GetAssetDetail() *AssetPreview {
	if x != nil {
		return x.AssetDetail
	}
	return nil
}

type GetItemsSharedByFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AssetDetail   []*SharedAssetPreview  `protobuf:"bytes,1,rep,name=asset_detail,json=assetDetail,proto3" json:"asset_detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemsSharedByFriendResponse) Reset() {
	*x = GetItemsSharedByFriendResponse{}
	mi := &file_proto_user_share_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemsSharedByFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemsSharedByFriendResponse) ProtoMessage() {}

func (x *GetItemsSharedByFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_share_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemsSharedByFriendResponse.ProtoReflect.Descriptor instead.
func (*GetItemsSharedByFriendResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_share_proto_rawDescGZIP(), []int{21}
}

func (x *GetItemsSharedByFriendResponse) GetAssetDetail() []*SharedAssetPreview {
	if x != nil {
		return x.AssetDetail
	}
	return nil
}

var File_proto_user_share_proto protoreflect.FileDescriptor

const file_proto_user_share_proto_rawDesc = "" +
	"\n" +
	"\x16proto/user/share.proto\x12\x04user\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18proto/user/preview.proto\"T\n" +
	"\vShareTarget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\bshare_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ashareAt\"\xe8\x01\n" +
	"\x10ShareItemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bitem_ids\x18\x02 \x03(\tR\aitemIds\x12\x1d\n" +
	"\n" +
	"item_types\x18\x03 \x03(\tR\titemTypes\x12)\n" +
	"\x06groups\x18\x04 \x03(\v2\x11.user.ShareTargetR\x06groups\x12+\n" +
	"\afriends\x18\x05 \x03(\v2\x11.user.ShareTargetR\afriends\x12)\n" +
	"\x06emails\x18\x06 \x03(\v2\x11.user.ShareTargetR\x06emails\"+\n" +
	"\x11ShareItemResponse\x12\x16\n" +
	"\x06finish\x18\x01 \x01(\bR\x06finish\"J\n" +
	"\x14GetGroupItemsRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"L\n" +
	"\x14GetFriendItemRequest\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\tR\bfriendId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"D\n" +
	"\x15GetGroupItemsResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.user.GroupItemDetailR\x05items\"\xd6\x01\n" +
	"\x0fGroupItemDetail\x12\"\n" +
	"\rgroup_item_id\x18\x01 \x01(\tR\vgroupItemId\x12\x1b\n" +
	"\tshared_by\x18\x02 \x01(\tR\bsharedBy\x127\n" +
	"\tshared_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bsharedAt\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x125\n" +
	"\fasset_detail\x18\x05 \x01(\v2\x12.user.AssetPreviewR\vassetDetail\"F\n" +
	"\x16GetFriendItemsResponse\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.user.FriendItemDetailR\x05items\"\xd9\x01\n" +
	"\x10FriendItemDetail\x12$\n" +
	"\x0efriend_item_id\x18\x01 \x01(\tR\ffriendItemId\x12\x1b\n" +
	"\tshared_by\x18\x02 \x01(\tR\bsharedBy\x127\n" +
	"\tshared_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\bsharedAt\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x125\n" +
	"\fasset_detail\x18\x05 \x01(\v2\x12.user.AssetPreviewR\vassetDetail\"F\n" +
	"\x12UnshareItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"4\n" +
	"\x15DeleteByEntityRequest\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\"2\n" +
	"\x16DeleteByEntityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"l\n" +
	"\x1bGetItemSharedTargetsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_type\x18\x03 \x01(\tR\bitemType\"\xc8\x01\n" +
	"\x0fSharedGroupInfo\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x1f\n" +
	"\vgroup_image\x18\x03 \x01(\tR\n" +
	"groupImage\x12!\n" +
	"\fmember_count\x18\x04 \x01(\x03R\vmemberCount\x127\n" +
	"\tshared_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bsharedAt\"\xa9\x01\n" +
	"\x10SharedFriendInfo\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\tR\bfriendId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12#\n" +
	"\rprofile_image\x18\x03 \x01(\tR\fprofileImage\x127\n" +
	"\tshared_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bsharedAt\"y\n" +
	"\x0fSharedEmailInfo\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x127\n" +
	"\tshared_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bsharedAt\x12\x17\n" +
	"\ais_sent\x18\x03 \x01(\bR\x06isSent\"\xae\x01\n" +
	"\x1cGetItemSharedTargetsResponse\x12-\n" +
	"\x06groups\x18\x01 \x03(\v2\x15.user.SharedGroupInfoR\x06groups\x120\n" +
	"\afriends\x18\x02 \x03(\v2\x16.user.SharedFriendInfoR\afriends\x12-\n" +
	"\x06emails\x18\x03 \x03(\v2\x15.user.SharedEmailInfoR\x06emails\"p\n" +
	"\x17GetSharedItemIDsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\"5\n" +
	"\x18GetSharedItemIDsResponse\x12\x19\n" +
	"\bitem_ids\x18\x01 \x03(\tR\aitemIds\"U\n" +
	"\x1dGetItemsSharedByFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\tR\bfriendId\"o\n" +
	"\x12SharedAssetPreview\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x125\n" +
	"\fasset_detail\x18\x03 \x01(\v2\x12.user.AssetPreviewR\vassetDetail\"]\n" +
	"\x1eGetItemsSharedByFriendResponse\x12;\n" +
	"\fasset_detail\x18\x01 \x03(\v2\x18.user.SharedAssetPreviewR\vassetDetailB\x15Z\x13wealth-vault/pkg/pbb\x06proto3"

var (
	file_proto_user_share_proto_rawDescOnce sync.Once
	file_proto_user_share_proto_rawDescData []byte
)

func file_proto_user_share_proto_rawDescGZIP() []byte {
	file_proto_user_share_proto_rawDescOnce.Do(func() {
		file_proto_user_share_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_share_proto_rawDesc), len(file_proto_user_share_proto_rawDesc)))
	})
	return file_proto_user_share_proto_rawDescData
}

var file_proto_user_share_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_user_share_proto_goTypes = []any{
	(*ShareTarget)(nil),                    // 0: user.ShareTarget
	(*ShareItemRequest)(nil),               // 1: user.ShareItemRequest
	(*ShareItemResponse)(nil),              // 2: user.ShareItemResponse
	(*GetGroupItemsRequest)(nil),           // 3: user.GetGroupItemsRequest
	(*GetFriendItemRequest)(nil),           // 4: user.GetFriendItemRequest
	(*GetGroupItemsResponse)(nil),          // 5: user.GetGroupItemsResponse
	(*GroupItemDetail)(nil),                // 6: user.GroupItemDetail
	(*GetFriendItemsResponse)(nil),         // 7: user.GetFriendItemsResponse
	(*FriendItemDetail)(nil),               // 8: user.FriendItemDetail
	(*UnshareItemRequest)(nil),             // 9: user.UnshareItemRequest
	(*DeleteByEntityRequest)(nil),          // 10: user.DeleteByEntityRequest
	(*DeleteByEntityResponse)(nil),         // 11: user.DeleteByEntityResponse
	(*GetItemSharedTargetsRequest)(nil),    // 12: user.GetItemSharedTargetsRequest
	(*SharedGroupInfo)(nil),                // 13: user.SharedGroupInfo
	(*SharedFriendInfo)(nil),               // 14: user.SharedFriendInfo
	(*SharedEmailInfo)(nil),                // 15: user.SharedEmailInfo
	(*GetItemSharedTargetsResponse)(nil),   // 16: user.GetItemSharedTargetsResponse
	(*GetSharedItemIDsRequest)(nil),        // 17: user.GetSharedItemIDsRequest
	(*GetSharedItemIDsResponse)(nil),       // 18: user.GetSharedItemIDsResponse
	(*GetItemsSharedByFriendRequest)(nil),  // 19: user.GetItemsSharedByFriendRequest
	(*SharedAssetPreview)(nil),             // 20: user.SharedAssetPreview
	(*GetItemsSharedByFriendResponse)(nil), // 21: user.GetItemsSharedByFriendResponse
	(*timestamppb.Timestamp)(nil),          // 22: google.protobuf.Timestamp
	(*AssetPreview)(nil),                   // 23: user.AssetPreview
}
var file_proto_user_share_proto_depIdxs = []int32{
	22, // 0: user.ShareTarget.share_at:type_name -> google.protobuf.Timestamp
	0,  // 1: user.ShareItemRequest.groups:type_name -> user.ShareTarget
	0,  // 2: user.ShareItemRequest.friends:type_name -> user.ShareTarget
	0,  // 3: user.ShareItemRequest.emails:type_name -> user.ShareTarget
	6,  // 4: user.GetGroupItemsResponse.items:type_name -> user.GroupItemDetail
	22, // 5: user.GroupItemDetail.shared_at:type_name -> google.protobuf.Timestamp
	23, // 6: user.GroupItemDetail.asset_detail:type_name -> user.AssetPreview
	8,  // 7: user.GetFriendItemsResponse.items:type_name -> user.FriendItemDetail
	22, // 8: user.FriendItemDetail.shared_at:type_name -> google.protobuf.Timestamp
	23, // 9: user.FriendItemDetail.asset_detail:type_name -> user.AssetPreview
	22, // 10: user.SharedGroupInfo.shared_at:type_name -> google.protobuf.Timestamp
	22, // 11: user.SharedFriendInfo.shared_at:type_name -> google.protobuf.Timestamp
	22, // 12: user.SharedEmailInfo.shared_at:type_name -> google.protobuf.Timestamp
	13, // 13: user.GetItemSharedTargetsResponse.groups:type_name -> user.SharedGroupInfo
	14, // 14: user.GetItemSharedTargetsResponse.friends:type_name -> user.SharedFriendInfo
	15, // 15: user.GetItemSharedTargetsResponse.emails:type_name -> user.SharedEmailInfo
	23, // 16: user.SharedAssetPreview.asset_detail:type_name -> user.AssetPreview
	20, // 17: user.GetItemsSharedByFriendResponse.asset_detail:type_name -> user.SharedAssetPreview
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_user_share_proto_init() }
func file_proto_user_share_proto_init() {
	if File_proto_user_share_proto != nil {
		return
	}
	file_proto_user_preview_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_share_proto_rawDesc), len(file_proto_user_share_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_user_share_proto_goTypes,
		DependencyIndexes: file_proto_user_share_proto_depIdxs,
		MessageInfos:      file_proto_user_share_proto_msgTypes,
	}.Build()
	File_proto_user_share_proto = out.File
	file_proto_user_share_proto_goTypes = nil
	file_proto_user_share_proto_depIdxs = nil
}
