// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/user/user_request.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_user_user_request_proto protoreflect.FileDescriptor

const file_proto_user_user_request_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/user/user_request.proto\x12\x04user\x1a\x15proto/user/user.proto\x1a\x16proto/user/group.proto\x1a\x16proto/user/share.proto\x1a\x18proto/user/message.proto2\xdb\x12\n" +
	"\vUserService\x129\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\x127\n" +
	"\aGetUser\x12\x18.user.GetUserByIDRequest\x1a\x12.user.UserResponse\x12F\n" +
	"\x0fGetUsersByEmail\x12\x1b.user.GetUserByEmailRequest\x1a\x16.user.UserInfoResponse\x129\n" +
	"\n" +
	"UpdateUser\x12\x17.user.UpdateUserRequest\x1a\x12.user.UserResponse\x12C\n" +
	"\rGetFriendList\x12\x18.user.GetUserByIDRequest\x1a\x18.user.FriendListResponse\x12H\n" +
	"\x12GetPendingRequests\x12\x18.user.GetUserByIDRequest\x1a\x18.user.FriendListResponse\x126\n" +
	"\tAddFriend\x12\x13.user.FriendRequest\x1a\x14.user.FriendResponse\x12?\n" +
	"\fAcceptFriend\x12\x19.user.AcceptFriendRequest\x1a\x14.user.FriendResponse\x12c\n" +
	"\x16GetItemsSharedByFriend\x12#.user.GetItemsSharedByFriendRequest\x1a$.user.GetItemsSharedByFriendResponse\x12K\n" +
	"\x0eSetCloseFriend\x12\x1b.user.SetCloseFriendRequest\x1a\x1c.user.SetCloseFriendResponse\x12N\n" +
	"\x0fGetCloseFriends\x12\x1c.user.GetCloseFriendsRequest\x1a\x1d.user.GetCloseFriendsResponse\x129\n" +
	"\fDeleteFriend\x12\x13.user.FriendRequest\x1a\x14.user.FriendResponse\x12<\n" +
	"\vCreateGroup\x12\x18.user.CreateGroupRequest\x1a\x13.user.GroupResponse\x12<\n" +
	"\vGetAllGroup\x12\x15.user.AllGroupRequest\x1a\x16.user.AllGroupResponse\x126\n" +
	"\bGetGroup\x12\x15.user.GetGroupRequest\x1a\x13.user.GroupResponse\x12H\n" +
	"\tGetMember\x12\x1c.user.GetGroupMembersRequest\x1a\x1d.user.GetGroupMembersResponse\x12<\n" +
	"\vUpdateGroup\x12\x18.user.UpdateGroupRequest\x1a\x13.user.GroupResponse\x12>\n" +
	"\x0eAddGroupMember\x12\x16.user.AddMemberRequest\x1a\x14.user.ActionResponse\x12F\n" +
	"\x14GrantGroupItemAccess\x12\x18.user.GrantAccessRequest\x1a\x14.user.ActionResponse\x12?\n" +
	"\fRemoveMember\x12\x19.user.RemoveMemberRequest\x1a\x14.user.ActionResponse\x12;\n" +
	"\n" +
	"LeaveGroup\x12\x17.user.LeaveGroupRequest\x1a\x14.user.ActionResponse\x12=\n" +
	"\vDeleteGroup\x12\x18.user.DeleteGroupRequest\x1a\x14.user.ActionResponse\x12<\n" +
	"\tShareItem\x12\x16.user.ShareItemRequest\x1a\x17.user.ShareItemResponse\x12H\n" +
	"\rGetSharedItem\x12\x1a.user.GetGroupItemsRequest\x1a\x1b.user.GetGroupItemsResponse\x12Q\n" +
	"\x15GetSharedIteminFriend\x12\x1a.user.GetFriendItemRequest\x1a\x1c.user.GetFriendItemsResponse\x12A\n" +
	"\fUnsharedItem\x12\x18.user.UnshareItemRequest\x1a\x17.user.ShareItemResponse\x12I\n" +
	"\x14UnsharedIteminFriend\x12\x18.user.UnshareItemRequest\x1a\x17.user.ShareItemResponse\x12Z\n" +
	"\x1dDeleteAllReferencesByEntityID\x12\x1b.user.DeleteByEntityRequest\x1a\x1c.user.DeleteByEntityResponse\x12]\n" +
	"\x14GetItemSharedTargets\x12!.user.GetItemSharedTargetsRequest\x1a\".user.GetItemSharedTargetsResponse\x12Q\n" +
	"\x10GetSharedItemIDs\x12\x1d.user.GetSharedItemIDsRequest\x1a\x1e.user.GetSharedItemIDsResponse\x12l\n" +
	"\x19GetAllSharedItemIDsByUser\x12&.user.GetAllSharedItemIDsByUserRequest\x1a'.user.GetAllSharedItemIDsByUserResponse\x12Q\n" +
	"\x10GetGroupMessages\x12\x1d.user.GetGroupMessagesRequest\x1a\x1e.user.GetGroupMessagesResponse\x12W\n" +
	"\x12GetPrivateMessages\x12\x1f.user.GetPrivateMessagesRequest\x1a .user.GetPrivateMessagesResponseB\x15Z\x13wealth-vault/pkg/pbb\x06proto3"

var file_proto_user_user_request_proto_goTypes = []any{
	(*CreateUserRequest)(nil),                 // 0: user.CreateUserRequest
	(*GetUserByIDRequest)(nil),                // 1: user.GetUserByIDRequest
	(*GetUserByEmailRequest)(nil),             // 2: user.GetUserByEmailRequest
	(*UpdateUserRequest)(nil),                 // 3: user.UpdateUserRequest
	(*FriendRequest)(nil),                     // 4: user.FriendRequest
	(*AcceptFriendRequest)(nil),               // 5: user.AcceptFriendRequest
	(*GetItemsSharedByFriendRequest)(nil),     // 6: user.GetItemsSharedByFriendRequest
	(*SetCloseFriendRequest)(nil),             // 7: user.SetCloseFriendRequest
	(*GetCloseFriendsRequest)(nil),            // 8: user.GetCloseFriendsRequest
	(*CreateGroupRequest)(nil),                // 9: user.CreateGroupRequest
	(*AllGroupRequest)(nil),                   // 10: user.AllGroupRequest
	(*GetGroupRequest)(nil),                   // 11: user.GetGroupRequest
	(*GetGroupMembersRequest)(nil),            // 12: user.GetGroupMembersRequest
	(*UpdateGroupRequest)(nil),                // 13: user.UpdateGroupRequest
	(*AddMemberRequest)(nil),                  // 14: user.AddMemberRequest
	(*GrantAccessRequest)(nil),                // 15: user.GrantAccessRequest
	(*RemoveMemberRequest)(nil),               // 16: user.RemoveMemberRequest
	(*LeaveGroupRequest)(nil),                 // 17: user.LeaveGroupRequest
	(*DeleteGroupRequest)(nil),                // 18: user.DeleteGroupRequest
	(*ShareItemRequest)(nil),                  // 19: user.ShareItemRequest
	(*GetGroupItemsRequest)(nil),              // 20: user.GetGroupItemsRequest
	(*GetFriendItemRequest)(nil),              // 21: user.GetFriendItemRequest
	(*UnshareItemRequest)(nil),                // 22: user.UnshareItemRequest
	(*DeleteByEntityRequest)(nil),             // 23: user.DeleteByEntityRequest
	(*GetItemSharedTargetsRequest)(nil),       // 24: user.GetItemSharedTargetsRequest
	(*GetSharedItemIDsRequest)(nil),           // 25: user.GetSharedItemIDsRequest
	(*GetAllSharedItemIDsByUserRequest)(nil),  // 26: user.GetAllSharedItemIDsByUserRequest
	(*GetGroupMessagesRequest)(nil),           // 27: user.GetGroupMessagesRequest
	(*GetPrivateMessagesRequest)(nil),         // 28: user.GetPrivateMessagesRequest
	(*UserResponse)(nil),                      // 29: user.UserResponse
	(*UserInfoResponse)(nil),                  // 30: user.UserInfoResponse
	(*FriendListResponse)(nil),                // 31: user.FriendListResponse
	(*FriendResponse)(nil),                    // 32: user.FriendResponse
	(*GetItemsSharedByFriendResponse)(nil),    // 33: user.GetItemsSharedByFriendResponse
	(*SetCloseFriendResponse)(nil),            // 34: user.SetCloseFriendResponse
	(*GetCloseFriendsResponse)(nil),           // 35: user.GetCloseFriendsResponse
	(*GroupResponse)(nil),                     // 36: user.GroupResponse
	(*AllGroupResponse)(nil),                  // 37: user.AllGroupResponse
	(*GetGroupMembersResponse)(nil),           // 38: user.GetGroupMembersResponse
	(*ActionResponse)(nil),                    // 39: user.ActionResponse
	(*ShareItemResponse)(nil),                 // 40: user.ShareItemResponse
	(*GetGroupItemsResponse)(nil),             // 41: user.GetGroupItemsResponse
	(*GetFriendItemsResponse)(nil),            // 42: user.GetFriendItemsResponse
	(*DeleteByEntityResponse)(nil),            // 43: user.DeleteByEntityResponse
	(*GetItemSharedTargetsResponse)(nil),      // 44: user.GetItemSharedTargetsResponse
	(*GetSharedItemIDsResponse)(nil),          // 45: user.GetSharedItemIDsResponse
	(*GetAllSharedItemIDsByUserResponse)(nil), // 46: user.GetAllSharedItemIDsByUserResponse
	(*GetGroupMessagesResponse)(nil),          // 47: user.GetGroupMessagesResponse
	(*GetPrivateMessagesResponse)(nil),        // 48: user.GetPrivateMessagesResponse
}
var file_proto_user_user_request_proto_depIdxs = []int32{
	0,  // 0: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	1,  // 1: user.UserService.GetUser:input_type -> user.GetUserByIDRequest
	2,  // 2: user.UserService.GetUsersByEmail:input_type -> user.GetUserByEmailRequest
	3,  // 3: user.UserService.UpdateUser:input_type -> user.UpdateUserRequest
	1,  // 4: user.UserService.GetFriendList:input_type -> user.GetUserByIDRequest
	1,  // 5: user.UserService.GetPendingRequests:input_type -> user.GetUserByIDRequest
	4,  // 6: user.UserService.AddFriend:input_type -> user.FriendRequest
	5,  // 7: user.UserService.AcceptFriend:input_type -> user.AcceptFriendRequest
	6,  // 8: user.UserService.GetItemsSharedByFriend:input_type -> user.GetItemsSharedByFriendRequest
	7,  // 9: user.UserService.SetCloseFriend:input_type -> user.SetCloseFriendRequest
	8,  // 10: user.UserService.GetCloseFriends:input_type -> user.GetCloseFriendsRequest
	4,  // 11: user.UserService.DeleteFriend:input_type -> user.FriendRequest
	9,  // 12: user.UserService.CreateGroup:input_type -> user.CreateGroupRequest
	10, // 13: user.UserService.GetAllGroup:input_type -> user.AllGroupRequest
	11, // 14: user.UserService.GetGroup:input_type -> user.GetGroupRequest
	12, // 15: user.UserService.GetMember:input_type -> user.GetGroupMembersRequest
	13, // 16: user.UserService.UpdateGroup:input_type -> user.UpdateGroupRequest
	14, // 17: user.UserService.AddGroupMember:input_type -> user.AddMemberRequest
	15, // 18: user.UserService.GrantGroupItemAccess:input_type -> user.GrantAccessRequest
	16, // 19: user.UserService.RemoveMember:input_type -> user.RemoveMemberRequest
	17, // 20: user.UserService.LeaveGroup:input_type -> user.LeaveGroupRequest
	18, // 21: user.UserService.DeleteGroup:input_type -> user.DeleteGroupRequest
	19, // 22: user.UserService.ShareItem:input_type -> user.ShareItemRequest
	20, // 23: user.UserService.GetSharedItem:input_type -> user.GetGroupItemsRequest
	21, // 24: user.UserService.GetSharedIteminFriend:input_type -> user.GetFriendItemRequest
	22, // 25: user.UserService.UnsharedItem:input_type -> user.UnshareItemRequest
	22, // 26: user.UserService.UnsharedIteminFriend:input_type -> user.UnshareItemRequest
	23, // 27: user.UserService.DeleteAllReferencesByEntityID:input_type -> user.DeleteByEntityRequest
	24, // 28: user.UserService.GetItemSharedTargets:input_type -> user.GetItemSharedTargetsRequest
	25, // 29: user.UserService.GetSharedItemIDs:input_type -> user.GetSharedItemIDsRequest
	26, // 30: user.UserService.GetAllSharedItemIDsByUser:input_type -> user.GetAllSharedItemIDsByUserRequest
	27, // 31: user.UserService.GetGroupMessages:input_type -> user.GetGroupMessagesRequest
	28, // 32: user.UserService.GetPrivateMessages:input_type -> user.GetPrivateMessagesRequest
	29, // 33: user.UserService.CreateUser:output_type -> user.UserResponse
	29, // 34: user.UserService.GetUser:output_type -> user.UserResponse
	30, // 35: user.UserService.GetUsersByEmail:output_type -> user.UserInfoResponse
	29, // 36: user.UserService.UpdateUser:output_type -> user.UserResponse
	31, // 37: user.UserService.GetFriendList:output_type -> user.FriendListResponse
	31, // 38: user.UserService.GetPendingRequests:output_type -> user.FriendListResponse
	32, // 39: user.UserService.AddFriend:output_type -> user.FriendResponse
	32, // 40: user.UserService.AcceptFriend:output_type -> user.FriendResponse
	33, // 41: user.UserService.GetItemsSharedByFriend:output_type -> user.GetItemsSharedByFriendResponse
	34, // 42: user.UserService.SetCloseFriend:output_type -> user.SetCloseFriendResponse
	35, // 43: user.UserService.GetCloseFriends:output_type -> user.GetCloseFriendsResponse
	32, // 44: user.UserService.DeleteFriend:output_type -> user.FriendResponse
	36, // 45: user.UserService.CreateGroup:output_type -> user.GroupResponse
	37, // 46: user.UserService.GetAllGroup:output_type -> user.AllGroupResponse
	36, // 47: user.UserService.GetGroup:output_type -> user.GroupResponse
	38, // 48: user.UserService.GetMember:output_type -> user.GetGroupMembersResponse
	36, // 49: user.UserService.UpdateGroup:output_type -> user.GroupResponse
	39, // 50: user.UserService.AddGroupMember:output_type -> user.ActionResponse
	39, // 51: user.UserService.GrantGroupItemAccess:output_type -> user.ActionResponse
	39, // 52: user.UserService.RemoveMember:output_type -> user.ActionResponse
	39, // 53: user.UserService.LeaveGroup:output_type -> user.ActionResponse
	39, // 54: user.UserService.DeleteGroup:output_type -> user.ActionResponse
	40, // 55: user.UserService.ShareItem:output_type -> user.ShareItemResponse
	41, // 56: user.UserService.GetSharedItem:output_type -> user.GetGroupItemsResponse
	42, // 57: user.UserService.GetSharedIteminFriend:output_type -> user.GetFriendItemsResponse
	40, // 58: user.UserService.UnsharedItem:output_type -> user.ShareItemResponse
	40, // 59: user.UserService.UnsharedIteminFriend:output_type -> user.ShareItemResponse
	43, // 60: user.UserService.DeleteAllReferencesByEntityID:output_type -> user.DeleteByEntityResponse
	44, // 61: user.UserService.GetItemSharedTargets:output_type -> user.GetItemSharedTargetsResponse
	45, // 62: user.UserService.GetSharedItemIDs:output_type -> user.GetSharedItemIDsResponse
	46, // 63: user.UserService.GetAllSharedItemIDsByUser:output_type -> user.GetAllSharedItemIDsByUserResponse
	47, // 64: user.UserService.GetGroupMessages:output_type -> user.GetGroupMessagesResponse
	48, // 65: user.UserService.GetPrivateMessages:output_type -> user.GetPrivateMessagesResponse
	33, // [33:66] is the sub-list for method output_type
	0,  // [0:33] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_user_request_proto_init() }
func file_proto_user_user_request_proto_init() {
	if File_proto_user_user_request_proto != nil {
		return
	}
	file_proto_user_user_proto_init()
	file_proto_user_group_proto_init()
	file_proto_user_share_proto_init()
	file_proto_user_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_user_request_proto_rawDesc), len(file_proto_user_user_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_user_request_proto_goTypes,
		DependencyIndexes: file_proto_user_user_request_proto_depIdxs,
	}.Build()
	File_proto_user_user_request_proto = out.File
	file_proto_user_user_request_proto_goTypes = nil
	file_proto_user_user_request_proto_depIdxs = nil
}
