# ---------- Build Stage ----------
FROM golang:1.25-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o asset-service ./cmd/main.go

# ---------- Runtime Stage ----------
FROM gcr.io/distroless/base-debian12

WORKDIR /app

ENV DB_HOST=postgres
ENV DB_PORT=5432
ENV DB_USER=admin
ENV DB_NAME=finaluser
ENV SSL_MODE=disable
ENV GRPC_PORT=50053

COPY --from=builder /app/asset-service /app/asset-service

EXPOSE 50053

CMD ["/app/asset-service"]