# ---------- Build Stage ----------
FROM golang:1.25-bookworm AS builder

WORKDIR /app

COPY proto/ ./proto/
COPY services/asset-service/go.mod services/asset-service/go.sum ./services/asset-service/

WORKDIR /app/services/asset-service
RUN go mod download

WORKDIR /app
COPY services/asset-service/ ./services/asset-service/

WORKDIR /app/services/asset-service
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/asset-service ./cmd/main.go

# ---------- Runtime Stage ----------
FROM gcr.io/distroless/base-debian12

WORKDIR /app

ENV DB_HOST=postgres
ENV DB_PORT=5432
ENV DB_USER=admin
ENV DB_NAME=asset_db
ENV SSL_MODE=disable
ENV GRPC_PORT=50053

COPY --from=builder /app/asset-service /app/asset-service

EXPOSE 50053

CMD ["/app/asset-service"]