// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/asset/asset_request.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_asset_asset_request_proto protoreflect.FileDescriptor

const file_proto_asset_asset_request_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/asset/asset_request.proto\x12\x05asset\x1a\x17proto/asset/asset.proto2\xa1\x03\n" +
	"\fAssetService\x12D\n" +
	"\vCreateAsset\x12\x19.asset.CreateAssetRequest\x1a\x1a.asset.CreateAssetResponse\x12>\n" +
	"\vUpdateAsset\x12\x19.asset.UpdateAssetRequest\x1a\x14.asset.AssetResponse\x12=\n" +
	"\bGetAsset\x12\x16.asset.GetAssetRequest\x1a\x19.asset.AssetArrayResponse\x12@\n" +
	"\fGetAssetByID\x12\x1a.asset.GetAssetByIDRequest\x1a\x14.asset.AssetResponse\x12D\n" +
	"\vDeleteAsset\x12\x19.asset.DeleteAssetRequest\x1a\x1a.asset.DeleteAssetResponse\x12D\n" +
	"\vGetNetWorth\x12\x19.asset.GetNetWorthRequest\x1a\x1a.asset.GetNetWorthResponseB\x15Z\x13wealth-vault/pkg/pbb\x06proto3"

var file_proto_asset_asset_request_proto_goTypes = []any{
	(*CreateAssetRequest)(nil),  // 0: asset.CreateAssetRequest
	(*UpdateAssetRequest)(nil),  // 1: asset.UpdateAssetRequest
	(*GetAssetRequest)(nil),     // 2: asset.GetAssetRequest
	(*GetAssetByIDRequest)(nil), // 3: asset.GetAssetByIDRequest
	(*DeleteAssetRequest)(nil),  // 4: asset.DeleteAssetRequest
	(*GetNetWorthRequest)(nil),  // 5: asset.GetNetWorthRequest
	(*CreateAssetResponse)(nil), // 6: asset.CreateAssetResponse
	(*AssetResponse)(nil),       // 7: asset.AssetResponse
	(*AssetArrayResponse)(nil),  // 8: asset.AssetArrayResponse
	(*DeleteAssetResponse)(nil), // 9: asset.DeleteAssetResponse
	(*GetNetWorthResponse)(nil), // 10: asset.GetNetWorthResponse
}
var file_proto_asset_asset_request_proto_depIdxs = []int32{
	0,  // 0: asset.AssetService.CreateAsset:input_type -> asset.CreateAssetRequest
	1,  // 1: asset.AssetService.UpdateAsset:input_type -> asset.UpdateAssetRequest
	2,  // 2: asset.AssetService.GetAsset:input_type -> asset.GetAssetRequest
	3,  // 3: asset.AssetService.GetAssetByID:input_type -> asset.GetAssetByIDRequest
	4,  // 4: asset.AssetService.DeleteAsset:input_type -> asset.DeleteAssetRequest
	5,  // 5: asset.AssetService.GetNetWorth:input_type -> asset.GetNetWorthRequest
	6,  // 6: asset.AssetService.CreateAsset:output_type -> asset.CreateAssetResponse
	7,  // 7: asset.AssetService.UpdateAsset:output_type -> asset.AssetResponse
	8,  // 8: asset.AssetService.GetAsset:output_type -> asset.AssetArrayResponse
	7,  // 9: asset.AssetService.GetAssetByID:output_type -> asset.AssetResponse
	9,  // 10: asset.AssetService.DeleteAsset:output_type -> asset.DeleteAssetResponse
	10, // 11: asset.AssetService.GetNetWorth:output_type -> asset.GetNetWorthResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_asset_asset_request_proto_init() }
func file_proto_asset_asset_request_proto_init() {
	if File_proto_asset_asset_request_proto != nil {
		return
	}
	file_proto_asset_asset_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_asset_asset_request_proto_rawDesc), len(file_proto_asset_asset_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_asset_asset_request_proto_goTypes,
		DependencyIndexes: file_proto_asset_asset_request_proto_depIdxs,
	}.Build()
	File_proto_asset_asset_request_proto = out.File
	file_proto_asset_asset_request_proto_goTypes = nil
	file_proto_asset_asset_request_proto_depIdxs = nil
}
