// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/asset/asset.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------Request/Response------
type GetAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetRequest) Reset() {
	*x = GetAssetRequest{}
	mi := &file_proto_asset_asset_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetRequest) ProtoMessage() {}

func (x *GetAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetRequest.ProtoReflect.Descriptor instead.
func (*GetAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{0}
}

func (x *GetAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAssetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAssetByIDRequest) Reset() {
	*x = GetAssetByIDRequest{}
	mi := &file_proto_asset_asset_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAssetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAssetByIDRequest) ProtoMessage() {}

func (x *GetAssetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAssetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetAssetByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{1}
}

func (x *GetAssetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAssetByIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBatchIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchIdsRequest) Reset() {
	*x = GetBatchIdsRequest{}
	mi := &file_proto_asset_asset_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchIdsRequest) ProtoMessage() {}

func (x *GetBatchIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchIdsRequest.ProtoReflect.Descriptor instead.
func (*GetBatchIdsRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{2}
}

func (x *GetBatchIdsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetNetWorthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetWorthRequest) Reset() {
	*x = GetNetWorthRequest{}
	mi := &file_proto_asset_asset_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetWorthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetWorthRequest) ProtoMessage() {}

func (x *GetNetWorthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetWorthRequest.ProtoReflect.Descriptor instead.
func (*GetNetWorthRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{3}
}

func (x *GetNetWorthRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetNetWorthResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ItemCount        int64                  `protobuf:"varint,1,opt,name=item_count,json=itemCount,proto3" json:"item_count,omitempty"`
	AssetsValue      float64                `protobuf:"fixed64,2,opt,name=assets_value,json=assetsValue,proto3" json:"assets_value,omitempty"`
	LiabilitiesValue float64                `protobuf:"fixed64,3,opt,name=liabilities_value,json=liabilitiesValue,proto3" json:"liabilities_value,omitempty"`
	NetWorth         float64                `protobuf:"fixed64,4,opt,name=net_worth,json=netWorth,proto3" json:"net_worth,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetNetWorthResponse) Reset() {
	*x = GetNetWorthResponse{}
	mi := &file_proto_asset_asset_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetWorthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetWorthResponse) ProtoMessage() {}

func (x *GetNetWorthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetWorthResponse.ProtoReflect.Descriptor instead.
func (*GetNetWorthResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{4}
}

func (x *GetNetWorthResponse) GetItemCount() int64 {
	if x != nil {
		return x.ItemCount
	}
	return 0
}

func (x *GetNetWorthResponse) GetAssetsValue() float64 {
	if x != nil {
		return x.AssetsValue
	}
	return 0
}

func (x *GetNetWorthResponse) GetLiabilitiesValue() float64 {
	if x != nil {
		return x.LiabilitiesValue
	}
	return 0
}

func (x *GetNetWorthResponse) GetNetWorth() float64 {
	if x != nil {
		return x.NetWorth
	}
	return 0
}

type DeleteAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetRequest) Reset() {
	*x = DeleteAssetRequest{}
	mi := &file_proto_asset_asset_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetRequest) ProtoMessage() {}

func (x *DeleteAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetRequest.ProtoReflect.Descriptor instead.
func (*DeleteAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAssetResponse) Reset() {
	*x = DeleteAssetResponse{}
	mi := &file_proto_asset_asset_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAssetResponse) ProtoMessage() {}

func (x *DeleteAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAssetResponse.ProtoReflect.Descriptor instead.
func (*DeleteAssetResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAssetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CheckAssetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAssetRequest) Reset() {
	*x = CheckAssetRequest{}
	mi := &file_proto_asset_asset_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAssetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAssetRequest) ProtoMessage() {}

func (x *CheckAssetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAssetRequest.ProtoReflect.Descriptor instead.
func (*CheckAssetRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{7}
}

func (x *CheckAssetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CheckAssetRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckAssetRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type CheckAssetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAssetResponse) Reset() {
	*x = CheckAssetResponse{}
	mi := &file_proto_asset_asset_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAssetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAssetResponse) ProtoMessage() {}

func (x *CheckAssetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAssetResponse.ProtoReflect.Descriptor instead.
func (*CheckAssetResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{8}
}

func (x *CheckAssetResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *CheckAssetResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetMyAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyAssetsRequest) Reset() {
	*x = GetMyAssetsRequest{}
	mi := &file_proto_asset_asset_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyAssetsRequest) ProtoMessage() {}

func (x *GetMyAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyAssetsRequest.ProtoReflect.Descriptor instead.
func (*GetMyAssetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{9}
}

func (x *GetMyAssetsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetMyAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIds    []string               `protobuf:"bytes,1,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	BuildingIds   []string               `protobuf:"bytes,2,rep,name=building_ids,json=buildingIds,proto3" json:"building_ids,omitempty"`
	CashIds       []string               `protobuf:"bytes,3,rep,name=cash_ids,json=cashIds,proto3" json:"cash_ids,omitempty"`
	InsuranceIds  []string               `protobuf:"bytes,4,rep,name=insurance_ids,json=insuranceIds,proto3" json:"insurance_ids,omitempty"`
	InvestmentIds []string               `protobuf:"bytes,5,rep,name=investment_ids,json=investmentIds,proto3" json:"investment_ids,omitempty"`
	LandIds       []string               `protobuf:"bytes,6,rep,name=land_ids,json=landIds,proto3" json:"land_ids,omitempty"`
	LiabilityIds  []string               `protobuf:"bytes,7,rep,name=liability_ids,json=liabilityIds,proto3" json:"liability_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyAssetsResponse) Reset() {
	*x = GetMyAssetsResponse{}
	mi := &file_proto_asset_asset_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyAssetsResponse) ProtoMessage() {}

func (x *GetMyAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyAssetsResponse.ProtoReflect.Descriptor instead.
func (*GetMyAssetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{10}
}

func (x *GetMyAssetsResponse) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

func (x *GetMyAssetsResponse) GetBuildingIds() []string {
	if x != nil {
		return x.BuildingIds
	}
	return nil
}

func (x *GetMyAssetsResponse) GetCashIds() []string {
	if x != nil {
		return x.CashIds
	}
	return nil
}

func (x *GetMyAssetsResponse) GetInsuranceIds() []string {
	if x != nil {
		return x.InsuranceIds
	}
	return nil
}

func (x *GetMyAssetsResponse) GetInvestmentIds() []string {
	if x != nil {
		return x.InvestmentIds
	}
	return nil
}

func (x *GetMyAssetsResponse) GetLandIds() []string {
	if x != nil {
		return x.LandIds
	}
	return nil
}

func (x *GetMyAssetsResponse) GetLiabilityIds() []string {
	if x != nil {
		return x.LiabilityIds
	}
	return nil
}

type AssetSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,4,opt,name=value,proto3" json:"value,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetSummary) Reset() {
	*x = AssetSummary{}
	mi := &file_proto_asset_asset_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetSummary) ProtoMessage() {}

func (x *AssetSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetSummary.ProtoReflect.Descriptor instead.
func (*AssetSummary) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{11}
}

func (x *AssetSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AssetSummary) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AssetSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AssetSummary) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AssetSummary) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *AssetSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetAllAssetsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAssetsRequest) Reset() {
	*x = GetAllAssetsRequest{}
	mi := &file_proto_asset_asset_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAssetsRequest) ProtoMessage() {}

func (x *GetAllAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAssetsRequest.ProtoReflect.Descriptor instead.
func (*GetAllAssetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{12}
}

func (x *GetAllAssetsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAllAssetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assets        []*AssetSummary        `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
	Liabilities   []*AssetSummary        `protobuf:"bytes,2,rep,name=liabilities,proto3" json:"liabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllAssetsResponse) Reset() {
	*x = GetAllAssetsResponse{}
	mi := &file_proto_asset_asset_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAssetsResponse) ProtoMessage() {}

func (x *GetAllAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_asset_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAssetsResponse.ProtoReflect.Descriptor instead.
func (*GetAllAssetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_asset_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllAssetsResponse) GetAssets() []*AssetSummary {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *GetAllAssetsResponse) GetLiabilities() []*AssetSummary {
	if x != nil {
		return x.Liabilities
	}
	return nil
}

var File_proto_asset_asset_proto protoreflect.FileDescriptor

const file_proto_asset_asset_proto_rawDesc = "" +
	"\n" +
	"\x17proto/asset/asset.proto\x12\x05asset\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x0fGetAssetRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\">\n" +
	"\x13GetAssetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"&\n" +
	"\x12GetBatchIdsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"-\n" +
	"\x12GetNetWorthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\xa1\x01\n" +
	"\x13GetNetWorthResponse\x12\x1d\n" +
	"\n" +
	"item_count\x18\x01 \x01(\x03R\titemCount\x12!\n" +
	"\fassets_value\x18\x02 \x01(\x01R\vassetsValue\x12+\n" +
	"\x11liabilities_value\x18\x03 \x01(\x01R\x10liabilitiesValue\x12\x1b\n" +
	"\tnet_worth\x18\x04 \x01(\x01R\bnetWorth\"=\n" +
	"\x12DeleteAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"/\n" +
	"\x13DeleteAssetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"P\n" +
	"\x11CheckAssetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"@\n" +
	"\x12CheckAssetResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"-\n" +
	"\x12GetMyAssetsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x80\x02\n" +
	"\x13GetMyAssetsResponse\x12\x1f\n" +
	"\vaccount_ids\x18\x01 \x03(\tR\n" +
	"accountIds\x12!\n" +
	"\fbuilding_ids\x18\x02 \x03(\tR\vbuildingIds\x12\x19\n" +
	"\bcash_ids\x18\x03 \x03(\tR\acashIds\x12#\n" +
	"\rinsurance_ids\x18\x04 \x03(\tR\finsuranceIds\x12%\n" +
	"\x0einvestment_ids\x18\x05 \x03(\tR\rinvestmentIds\x12\x19\n" +
	"\bland_ids\x18\x06 \x03(\tR\alandIds\x12#\n" +
	"\rliability_ids\x18\a \x03(\tR\fliabilityIds\"\xad\x01\n" +
	"\fAssetSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x04 \x01(\x01R\x05value\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\".\n" +
	"\x13GetAllAssetsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"z\n" +
	"\x14GetAllAssetsResponse\x12+\n" +
	"\x06assets\x18\x01 \x03(\v2\x13.asset.AssetSummaryR\x06assets\x125\n" +
	"\vliabilities\x18\x02 \x03(\v2\x13.asset.AssetSummaryR\vliabilitiesB\x15Z\x13wealth-vault/pkg/pbb\x06proto3"

var (
	file_proto_asset_asset_proto_rawDescOnce sync.Once
	file_proto_asset_asset_proto_rawDescData []byte
)

func file_proto_asset_asset_proto_rawDescGZIP() []byte {
	file_proto_asset_asset_proto_rawDescOnce.Do(func() {
		file_proto_asset_asset_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_asset_asset_proto_rawDesc), len(file_proto_asset_asset_proto_rawDesc)))
	})
	return file_proto_asset_asset_proto_rawDescData
}

var file_proto_asset_asset_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_asset_asset_proto_goTypes = []any{
	(*GetAssetRequest)(nil),       // 0: asset.GetAssetRequest
	(*GetAssetByIDRequest)(nil),   // 1: asset.GetAssetByIDRequest
	(*GetBatchIdsRequest)(nil),    // 2: asset.GetBatchIdsRequest
	(*GetNetWorthRequest)(nil),    // 3: asset.GetNetWorthRequest
	(*GetNetWorthResponse)(nil),   // 4: asset.GetNetWorthResponse
	(*DeleteAssetRequest)(nil),    // 5: asset.DeleteAssetRequest
	(*DeleteAssetResponse)(nil),   // 6: asset.DeleteAssetResponse
	(*CheckAssetRequest)(nil),     // 7: asset.CheckAssetRequest
	(*CheckAssetResponse)(nil),    // 8: asset.CheckAssetResponse
	(*GetMyAssetsRequest)(nil),    // 9: asset.GetMyAssetsRequest
	(*GetMyAssetsResponse)(nil),   // 10: asset.GetMyAssetsResponse
	(*AssetSummary)(nil),          // 11: asset.AssetSummary
	(*GetAllAssetsRequest)(nil),   // 12: asset.GetAllAssetsRequest
	(*GetAllAssetsResponse)(nil),  // 13: asset.GetAllAssetsResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_proto_asset_asset_proto_depIdxs = []int32{
	14, // 0: asset.AssetSummary.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: asset.GetAllAssetsResponse.assets:type_name -> asset.AssetSummary
	11, // 2: asset.GetAllAssetsResponse.liabilities:type_name -> asset.AssetSummary
	3,  // [3:3] is the sub-list for method output_type
	3,  // [3:3] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_asset_asset_proto_init() }
func file_proto_asset_asset_proto_init() {
	if File_proto_asset_asset_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_asset_asset_proto_rawDesc), len(file_proto_asset_asset_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_asset_asset_proto_goTypes,
		DependencyIndexes: file_proto_asset_asset_proto_depIdxs,
		MessageInfos:      file_proto_asset_asset_proto_msgTypes,
	}.Build()
	File_proto_asset_asset_proto = out.File
	file_proto_asset_asset_proto_goTypes = nil
	file_proto_asset_asset_proto_depIdxs = nil
}
