// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/asset/account.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BankAccType int32

const (
	BankAccType_BANK_ACC_TYPE_UNSPECIFIED   BankAccType = 0
	BankAccType_BANK_ACC_TYPE_SAVINGS       BankAccType = 1 // ออมทรัพย์
	BankAccType_BANK_ACC_TYPE_CURRENT       BankAccType = 2 // กระแสรายวัน
	BankAccType_BANK_ACC_TYPE_FIXED_DEPOSIT BankAccType = 3 // ฝากประจำ
)

// Enum value maps for BankAccType.
var (
	BankAccType_name = map[int32]string{
		0: "BANK_ACC_TYPE_UNSPECIFIED",
		1: "BANK_ACC_TYPE_SAVINGS",
		2: "BANK_ACC_TYPE_CURRENT",
		3: "BANK_ACC_TYPE_FIXED_DEPOSIT",
	}
	BankAccType_value = map[string]int32{
		"BANK_ACC_TYPE_UNSPECIFIED":   0,
		"BANK_ACC_TYPE_SAVINGS":       1,
		"BANK_ACC_TYPE_CURRENT":       2,
		"BANK_ACC_TYPE_FIXED_DEPOSIT": 3,
	}
)

func (x BankAccType) Enum() *BankAccType {
	p := new(BankAccType)
	*p = x
	return p
}

func (x BankAccType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BankAccType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_asset_account_proto_enumTypes[0].Descriptor()
}

func (BankAccType) Type() protoreflect.EnumType {
	return &file_proto_asset_account_proto_enumTypes[0]
}

func (x BankAccType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BankAccType.Descriptor instead.
func (BankAccType) EnumDescriptor() ([]byte, []int) {
	return file_proto_asset_account_proto_rawDescGZIP(), []int{0}
}

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	BankName      string                 `protobuf:"bytes,4,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BankAcc       string                 `protobuf:"bytes,5,opt,name=bank_acc,json=bankAcc,proto3" json:"bank_acc,omitempty"`
	Type          BankAccType            `protobuf:"varint,6,opt,name=type,proto3,enum=asset.BankAccType" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Files         []*FileInfo            `protobuf:"bytes,9,rep,name=files,proto3" json:"files,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_asset_account_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_account_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_asset_account_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *Account) GetBankAcc() string {
	if x != nil {
		return x.BankAcc
	}
	return ""
}

func (x *Account) GetType() BankAccType {
	if x != nil {
		return x.Type
	}
	return BankAccType_BANK_ACC_TYPE_UNSPECIFIED
}

func (x *Account) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Account) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Account) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Account) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Account) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BankName      string                 `protobuf:"bytes,3,opt,name=bank_name,json=bankName,proto3" json:"bank_name,omitempty"`
	BankAcc       string                 `protobuf:"bytes,4,opt,name=bank_acc,json=bankAcc,proto3" json:"bank_acc,omitempty"`
	Type          BankAccType            `protobuf:"varint,5,opt,name=type,proto3,enum=asset.BankAccType" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	NewFiles      []*FileInfo            `protobuf:"bytes,8,rep,name=new_files,json=newFiles,proto3" json:"new_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_asset_account_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_account_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_account_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetBankName() string {
	if x != nil {
		return x.BankName
	}
	return ""
}

func (x *CreateAccountRequest) GetBankAcc() string {
	if x != nil {
		return x.BankAcc
	}
	return ""
}

func (x *CreateAccountRequest) GetType() BankAccType {
	if x != nil {
		return x.Type
	}
	return BankAccType_BANK_ACC_TYPE_UNSPECIFIED
}

func (x *CreateAccountRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateAccountRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAccountRequest) GetNewFiles() []*FileInfo {
	if x != nil {
		return x.NewFiles
	}
	return nil
}

type UpdateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Acc           *Account               `protobuf:"bytes,2,opt,name=acc,proto3" json:"acc,omitempty"`
	NewFiles      []*FileInfo            `protobuf:"bytes,3,rep,name=new_files,json=newFiles,proto3" json:"new_files,omitempty"`
	DeleteFileIds []string               `protobuf:"bytes,4,rep,name=delete_file_ids,json=deleteFileIds,proto3" json:"delete_file_ids,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_proto_asset_account_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_account_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_account_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateAccountRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAccountRequest) GetAcc() *Account {
	if x != nil {
		return x.Acc
	}
	return nil
}

func (x *UpdateAccountRequest) GetNewFiles() []*FileInfo {
	if x != nil {
		return x.NewFiles
	}
	return nil
}

func (x *UpdateAccountRequest) GetDeleteFileIds() []string {
	if x != nil {
		return x.DeleteFileIds
	}
	return nil
}

func (x *UpdateAccountRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type AccountArrayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Account       []*Account             `protobuf:"bytes,2,rep,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountArrayResponse) Reset() {
	*x = AccountArrayResponse{}
	mi := &file_proto_asset_account_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountArrayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountArrayResponse) ProtoMessage() {}

func (x *AccountArrayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_account_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountArrayResponse.ProtoReflect.Descriptor instead.
func (*AccountArrayResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_account_proto_rawDescGZIP(), []int{3}
}

func (x *AccountArrayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AccountArrayResponse) GetAccount() []*Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type AccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Account       *Account               `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountResponse) Reset() {
	*x = AccountResponse{}
	mi := &file_proto_asset_account_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountResponse) ProtoMessage() {}

func (x *AccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_account_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountResponse.ProtoReflect.Descriptor instead.
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_account_proto_rawDescGZIP(), []int{4}
}

func (x *AccountResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

var File_proto_asset_account_proto protoreflect.FileDescriptor

const file_proto_asset_account_proto_rawDesc = "" +
	"\n" +
	"\x19proto/asset/account.proto\x12\x05asset\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x16proto/asset/file.proto\"\xfd\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tbank_name\x18\x04 \x01(\tR\bbankName\x12\x19\n" +
	"\bbank_acc\x18\x05 \x01(\tR\abankAcc\x12&\n" +
	"\x04type\x18\x06 \x01(\x0e2\x12.asset.BankAccTypeR\x04type\x12\x16\n" +
	"\x06amount\x18\a \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12%\n" +
	"\x05files\x18\t \x03(\v2\x0f.asset.FileInfoR\x05files\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8b\x02\n" +
	"\x14CreateAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tbank_name\x18\x03 \x01(\tR\bbankName\x12\x19\n" +
	"\bbank_acc\x18\x04 \x01(\tR\abankAcc\x12&\n" +
	"\x04type\x18\x05 \x01(\x0e2\x12.asset.BankAccTypeR\x04type\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12,\n" +
	"\tnew_files\x18\b \x03(\v2\x0f.asset.FileInfoR\bnewFiles\"\xdb\x01\n" +
	"\x14UpdateAccountRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\x03acc\x18\x02 \x01(\v2\x0e.asset.AccountR\x03acc\x12,\n" +
	"\tnew_files\x18\x03 \x03(\v2\x0f.asset.FileInfoR\bnewFiles\x12&\n" +
	"\x0fdelete_file_ids\x18\x04 \x03(\tR\rdeleteFileIds\x12;\n" +
	"\vupdate_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"Z\n" +
	"\x14AccountArrayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\aaccount\x18\x02 \x03(\v2\x0e.asset.AccountR\aaccount\"U\n" +
	"\x0fAccountResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\aaccount\x18\x02 \x01(\v2\x0e.asset.AccountR\aaccount*\x83\x01\n" +
	"\vBankAccType\x12\x1d\n" +
	"\x19BANK_ACC_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15BANK_ACC_TYPE_SAVINGS\x10\x01\x12\x19\n" +
	"\x15BANK_ACC_TYPE_CURRENT\x10\x02\x12\x1f\n" +
	"\x1bBANK_ACC_TYPE_FIXED_DEPOSIT\x10\x03B\x15Z\x13wealth-vault/pkg/pbb\x06proto3"

var (
	file_proto_asset_account_proto_rawDescOnce sync.Once
	file_proto_asset_account_proto_rawDescData []byte
)

func file_proto_asset_account_proto_rawDescGZIP() []byte {
	file_proto_asset_account_proto_rawDescOnce.Do(func() {
		file_proto_asset_account_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_asset_account_proto_rawDesc), len(file_proto_asset_account_proto_rawDesc)))
	})
	return file_proto_asset_account_proto_rawDescData
}

var file_proto_asset_account_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_asset_account_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_asset_account_proto_goTypes = []any{
	(BankAccType)(0),              // 0: asset.BankAccType
	(*Account)(nil),               // 1: asset.Account
	(*CreateAccountRequest)(nil),  // 2: asset.CreateAccountRequest
	(*UpdateAccountRequest)(nil),  // 3: asset.UpdateAccountRequest
	(*AccountArrayResponse)(nil),  // 4: asset.AccountArrayResponse
	(*AccountResponse)(nil),       // 5: asset.AccountResponse
	(*FileInfo)(nil),              // 6: asset.FileInfo
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 8: google.protobuf.FieldMask
}
var file_proto_asset_account_proto_depIdxs = []int32{
	0,  // 0: asset.Account.type:type_name -> asset.BankAccType
	6,  // 1: asset.Account.files:type_name -> asset.FileInfo
	7,  // 2: asset.Account.created_at:type_name -> google.protobuf.Timestamp
	7,  // 3: asset.Account.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: asset.CreateAccountRequest.type:type_name -> asset.BankAccType
	6,  // 5: asset.CreateAccountRequest.new_files:type_name -> asset.FileInfo
	1,  // 6: asset.UpdateAccountRequest.acc:type_name -> asset.Account
	6,  // 7: asset.UpdateAccountRequest.new_files:type_name -> asset.FileInfo
	8,  // 8: asset.UpdateAccountRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 9: asset.AccountArrayResponse.account:type_name -> asset.Account
	1,  // 10: asset.AccountResponse.account:type_name -> asset.Account
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_asset_account_proto_init() }
func file_proto_asset_account_proto_init() {
	if File_proto_asset_account_proto != nil {
		return
	}
	file_proto_asset_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_asset_account_proto_rawDesc), len(file_proto_asset_account_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_asset_account_proto_goTypes,
		DependencyIndexes: file_proto_asset_account_proto_depIdxs,
		EnumInfos:         file_proto_asset_account_proto_enumTypes,
		MessageInfos:      file_proto_asset_account_proto_msgTypes,
	}.Build()
	File_proto_asset_account_proto = out.File
	file_proto_asset_account_proto_goTypes = nil
	file_proto_asset_account_proto_depIdxs = nil
}
