// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/asset/investment.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvestmentType int32

const (
	InvestmentType_INVEST_TYPE_UNSPECIFIED InvestmentType = 0
	InvestmentType_INVEST_TYPE_STOCK_TH    InvestmentType = 1 // หุ้นไทย
	InvestmentType_INVEST_TYPE_STOCK_US    InvestmentType = 2 // หุ้นนอก
	InvestmentType_INVEST_TYPE_MUTUAL_FUND InvestmentType = 3 // กองทุนรวม
	InvestmentType_INVEST_TYPE_BOND        InvestmentType = 4 // พันธบัตร/หุ้นกู้
	InvestmentType_INVEST_TYPE_CRYPTO      InvestmentType = 5 // Cryptocurrency
	InvestmentType_INVEST_TYPE_GOLD        InvestmentType = 6 // ทองคำ (Digital/Paper)
)

// Enum value maps for InvestmentType.
var (
	InvestmentType_name = map[int32]string{
		0: "INVEST_TYPE_UNSPECIFIED",
		1: "INVEST_TYPE_STOCK_TH",
		2: "INVEST_TYPE_STOCK_US",
		3: "INVEST_TYPE_MUTUAL_FUND",
		4: "INVEST_TYPE_BOND",
		5: "INVEST_TYPE_CRYPTO",
		6: "INVEST_TYPE_GOLD",
	}
	InvestmentType_value = map[string]int32{
		"INVEST_TYPE_UNSPECIFIED": 0,
		"INVEST_TYPE_STOCK_TH":    1,
		"INVEST_TYPE_STOCK_US":    2,
		"INVEST_TYPE_MUTUAL_FUND": 3,
		"INVEST_TYPE_BOND":        4,
		"INVEST_TYPE_CRYPTO":      5,
		"INVEST_TYPE_GOLD":        6,
	}
)

func (x InvestmentType) Enum() *InvestmentType {
	p := new(InvestmentType)
	*p = x
	return p
}

func (x InvestmentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvestmentType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_asset_investment_proto_enumTypes[0].Descriptor()
}

func (InvestmentType) Type() protoreflect.EnumType {
	return &file_proto_asset_investment_proto_enumTypes[0]
}

func (x InvestmentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvestmentType.Descriptor instead.
func (InvestmentType) EnumDescriptor() ([]byte, []int) {
	return file_proto_asset_investment_proto_rawDescGZIP(), []int{0}
}

type Investment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Type          InvestmentType         `protobuf:"varint,5,opt,name=type,proto3,enum=asset.InvestmentType" json:"type,omitempty"`
	BrokerName    string                 `protobuf:"bytes,6,opt,name=broker_name,json=brokerName,proto3" json:"broker_name,omitempty"`
	Quantity      float64                `protobuf:"fixed64,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CostPrice     float64                `protobuf:"fixed64,8,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	Amount        float64                `protobuf:"fixed64,9,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	Files         []*FileInfo            `protobuf:"bytes,11,rep,name=files,proto3" json:"files,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Investment) Reset() {
	*x = Investment{}
	mi := &file_proto_asset_investment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Investment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Investment) ProtoMessage() {}

func (x *Investment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_investment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Investment.ProtoReflect.Descriptor instead.
func (*Investment) Descriptor() ([]byte, []int) {
	return file_proto_asset_investment_proto_rawDescGZIP(), []int{0}
}

func (x *Investment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Investment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Investment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Investment) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Investment) GetType() InvestmentType {
	if x != nil {
		return x.Type
	}
	return InvestmentType_INVEST_TYPE_UNSPECIFIED
}

func (x *Investment) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

func (x *Investment) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Investment) GetCostPrice() float64 {
	if x != nil {
		return x.CostPrice
	}
	return 0
}

func (x *Investment) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Investment) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Investment) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Investment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Investment) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Investment) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type CreateInvestmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Type          InvestmentType         `protobuf:"varint,4,opt,name=type,proto3,enum=asset.InvestmentType" json:"type,omitempty"`
	BrokerName    string                 `protobuf:"bytes,5,opt,name=broker_name,json=brokerName,proto3" json:"broker_name,omitempty"`
	Quantity      float64                `protobuf:"fixed64,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CostPrice     float64                `protobuf:"fixed64,7,opt,name=cost_price,json=costPrice,proto3" json:"cost_price,omitempty"`
	Amount        float64                `protobuf:"fixed64,8,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	NewFiles      []*FileInfo            `protobuf:"bytes,10,rep,name=new_files,json=newFiles,proto3" json:"new_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInvestmentRequest) Reset() {
	*x = CreateInvestmentRequest{}
	mi := &file_proto_asset_investment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInvestmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInvestmentRequest) ProtoMessage() {}

func (x *CreateInvestmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_investment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInvestmentRequest.ProtoReflect.Descriptor instead.
func (*CreateInvestmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_investment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInvestmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateInvestmentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateInvestmentRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CreateInvestmentRequest) GetType() InvestmentType {
	if x != nil {
		return x.Type
	}
	return InvestmentType_INVEST_TYPE_UNSPECIFIED
}

func (x *CreateInvestmentRequest) GetBrokerName() string {
	if x != nil {
		return x.BrokerName
	}
	return ""
}

func (x *CreateInvestmentRequest) GetQuantity() float64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateInvestmentRequest) GetCostPrice() float64 {
	if x != nil {
		return x.CostPrice
	}
	return 0
}

func (x *CreateInvestmentRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateInvestmentRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateInvestmentRequest) GetNewFiles() []*FileInfo {
	if x != nil {
		return x.NewFiles
	}
	return nil
}

type UpdateInvestmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Invest        *Investment            `protobuf:"bytes,2,opt,name=invest,proto3" json:"invest,omitempty"`
	NewFiles      []*FileInfo            `protobuf:"bytes,3,rep,name=new_files,json=newFiles,proto3" json:"new_files,omitempty"`
	DeleteFileIds []string               `protobuf:"bytes,4,rep,name=delete_file_ids,json=deleteFileIds,proto3" json:"delete_file_ids,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,5,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInvestmentRequest) Reset() {
	*x = UpdateInvestmentRequest{}
	mi := &file_proto_asset_investment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInvestmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInvestmentRequest) ProtoMessage() {}

func (x *UpdateInvestmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_investment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInvestmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateInvestmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_investment_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateInvestmentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateInvestmentRequest) GetInvest() *Investment {
	if x != nil {
		return x.Invest
	}
	return nil
}

func (x *UpdateInvestmentRequest) GetNewFiles() []*FileInfo {
	if x != nil {
		return x.NewFiles
	}
	return nil
}

func (x *UpdateInvestmentRequest) GetDeleteFileIds() []string {
	if x != nil {
		return x.DeleteFileIds
	}
	return nil
}

func (x *UpdateInvestmentRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type InvestmentArrayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Invest        []*Investment          `protobuf:"bytes,2,rep,name=invest,proto3" json:"invest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvestmentArrayResponse) Reset() {
	*x = InvestmentArrayResponse{}
	mi := &file_proto_asset_investment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestmentArrayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestmentArrayResponse) ProtoMessage() {}

func (x *InvestmentArrayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_investment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestmentArrayResponse.ProtoReflect.Descriptor instead.
func (*InvestmentArrayResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_investment_proto_rawDescGZIP(), []int{3}
}

func (x *InvestmentArrayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InvestmentArrayResponse) GetInvest() []*Investment {
	if x != nil {
		return x.Invest
	}
	return nil
}

type InvestmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Invest        *Investment            `protobuf:"bytes,2,opt,name=invest,proto3" json:"invest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvestmentResponse) Reset() {
	*x = InvestmentResponse{}
	mi := &file_proto_asset_investment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestmentResponse) ProtoMessage() {}

func (x *InvestmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_investment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestmentResponse.ProtoReflect.Descriptor instead.
func (*InvestmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_investment_proto_rawDescGZIP(), []int{4}
}

func (x *InvestmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InvestmentResponse) GetInvest() *Investment {
	if x != nil {
		return x.Invest
	}
	return nil
}

var File_proto_asset_investment_proto protoreflect.FileDescriptor

const file_proto_asset_investment_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/asset/investment.proto\x12\x05asset\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x16proto/asset/file.proto\"\xfa\x03\n" +
	"\n" +
	"Investment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12)\n" +
	"\x04type\x18\x05 \x01(\x0e2\x15.asset.InvestmentTypeR\x04type\x12\x1f\n" +
	"\vbroker_name\x18\x06 \x01(\tR\n" +
	"brokerName\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x01R\bquantity\x12\x1d\n" +
	"\n" +
	"cost_price\x18\b \x01(\x01R\tcostPrice\x12\x16\n" +
	"\x06amount\x18\t \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12%\n" +
	"\x05files\x18\v \x03(\v2\x0f.asset.FileInfoR\x05files\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\xcd\x02\n" +
	"\x17CreateInvestmentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12)\n" +
	"\x04type\x18\x04 \x01(\x0e2\x15.asset.InvestmentTypeR\x04type\x12\x1f\n" +
	"\vbroker_name\x18\x05 \x01(\tR\n" +
	"brokerName\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x01R\bquantity\x12\x1d\n" +
	"\n" +
	"cost_price\x18\a \x01(\x01R\tcostPrice\x12\x16\n" +
	"\x06amount\x18\b \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12,\n" +
	"\tnew_files\x18\n" +
	" \x03(\v2\x0f.asset.FileInfoR\bnewFiles\"\xe7\x01\n" +
	"\x17UpdateInvestmentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12)\n" +
	"\x06invest\x18\x02 \x01(\v2\x11.asset.InvestmentR\x06invest\x12,\n" +
	"\tnew_files\x18\x03 \x03(\v2\x0f.asset.FileInfoR\bnewFiles\x12&\n" +
	"\x0fdelete_file_ids\x18\x04 \x03(\tR\rdeleteFileIds\x12;\n" +
	"\vupdate_mask\x18\x05 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"^\n" +
	"\x17InvestmentArrayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x06invest\x18\x02 \x03(\v2\x11.asset.InvestmentR\x06invest\"Y\n" +
	"\x12InvestmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x06invest\x18\x02 \x01(\v2\x11.asset.InvestmentR\x06invest*\xc2\x01\n" +
	"\x0eInvestmentType\x12\x1b\n" +
	"\x17INVEST_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14INVEST_TYPE_STOCK_TH\x10\x01\x12\x18\n" +
	"\x14INVEST_TYPE_STOCK_US\x10\x02\x12\x1b\n" +
	"\x17INVEST_TYPE_MUTUAL_FUND\x10\x03\x12\x14\n" +
	"\x10INVEST_TYPE_BOND\x10\x04\x12\x16\n" +
	"\x12INVEST_TYPE_CRYPTO\x10\x05\x12\x14\n" +
	"\x10INVEST_TYPE_GOLD\x10\x06B\x15Z\x13wealth-vault/pkg/pbb\x06proto3"

var (
	file_proto_asset_investment_proto_rawDescOnce sync.Once
	file_proto_asset_investment_proto_rawDescData []byte
)

func file_proto_asset_investment_proto_rawDescGZIP() []byte {
	file_proto_asset_investment_proto_rawDescOnce.Do(func() {
		file_proto_asset_investment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_asset_investment_proto_rawDesc), len(file_proto_asset_investment_proto_rawDesc)))
	})
	return file_proto_asset_investment_proto_rawDescData
}

var file_proto_asset_investment_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_asset_investment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_asset_investment_proto_goTypes = []any{
	(InvestmentType)(0),             // 0: asset.InvestmentType
	(*Investment)(nil),              // 1: asset.Investment
	(*CreateInvestmentRequest)(nil), // 2: asset.CreateInvestmentRequest
	(*UpdateInvestmentRequest)(nil), // 3: asset.UpdateInvestmentRequest
	(*InvestmentArrayResponse)(nil), // 4: asset.InvestmentArrayResponse
	(*InvestmentResponse)(nil),      // 5: asset.InvestmentResponse
	(*FileInfo)(nil),                // 6: asset.FileInfo
	(*timestamppb.Timestamp)(nil),   // 7: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),   // 8: google.protobuf.FieldMask
}
var file_proto_asset_investment_proto_depIdxs = []int32{
	0,  // 0: asset.Investment.type:type_name -> asset.InvestmentType
	6,  // 1: asset.Investment.files:type_name -> asset.FileInfo
	7,  // 2: asset.Investment.created_at:type_name -> google.protobuf.Timestamp
	7,  // 3: asset.Investment.updated_at:type_name -> google.protobuf.Timestamp
	7,  // 4: asset.Investment.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 5: asset.CreateInvestmentRequest.type:type_name -> asset.InvestmentType
	6,  // 6: asset.CreateInvestmentRequest.new_files:type_name -> asset.FileInfo
	1,  // 7: asset.UpdateInvestmentRequest.invest:type_name -> asset.Investment
	6,  // 8: asset.UpdateInvestmentRequest.new_files:type_name -> asset.FileInfo
	8,  // 9: asset.UpdateInvestmentRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 10: asset.InvestmentArrayResponse.invest:type_name -> asset.Investment
	1,  // 11: asset.InvestmentResponse.invest:type_name -> asset.Investment
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_asset_investment_proto_init() }
func file_proto_asset_investment_proto_init() {
	if File_proto_asset_investment_proto != nil {
		return
	}
	file_proto_asset_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_asset_investment_proto_rawDesc), len(file_proto_asset_investment_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_asset_investment_proto_goTypes,
		DependencyIndexes: file_proto_asset_investment_proto_depIdxs,
		EnumInfos:         file_proto_asset_investment_proto_enumTypes,
		MessageInfos:      file_proto_asset_investment_proto_msgTypes,
	}.Build()
	File_proto_asset_investment_proto = out.File
	file_proto_asset_investment_proto_goTypes = nil
	file_proto_asset_investment_proto_depIdxs = nil
}
