// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/asset/liability.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Liability struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Creditor             string                 `protobuf:"bytes,3,opt,name=creditor,proto3" json:"creditor,omitempty"`
	Type                 LiabilityType          `protobuf:"varint,4,opt,name=type,proto3,enum=asset.LiabilityType" json:"type,omitempty"`
	Principal            float64                `protobuf:"fixed64,5,opt,name=principal,proto3" json:"principal,omitempty"`
	InterestRate         float64                `protobuf:"fixed64,6,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	IsIncludedInNetWorth bool                   `protobuf:"varint,7,opt,name=is_included_in_net_worth,json=isIncludedInNetWorth,proto3" json:"is_included_in_net_worth,omitempty"`
	StartAt              *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt                *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Description          string                 `protobuf:"bytes,10,opt,name=description,proto3" json:"description,omitempty"`
	CreatedBy            string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Files                []*FileInfo            `protobuf:"bytes,12,rep,name=files,proto3" json:"files,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Liability) Reset() {
	*x = Liability{}
	mi := &file_proto_asset_liability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Liability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Liability) ProtoMessage() {}

func (x *Liability) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_liability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Liability.ProtoReflect.Descriptor instead.
func (*Liability) Descriptor() ([]byte, []int) {
	return file_proto_asset_liability_proto_rawDescGZIP(), []int{0}
}

func (x *Liability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Liability) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Liability) GetCreditor() string {
	if x != nil {
		return x.Creditor
	}
	return ""
}

func (x *Liability) GetType() LiabilityType {
	if x != nil {
		return x.Type
	}
	return LiabilityType_LIABILITY_TYPE_UNSPECIFIED
}

func (x *Liability) GetPrincipal() float64 {
	if x != nil {
		return x.Principal
	}
	return 0
}

func (x *Liability) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *Liability) GetIsIncludedInNetWorth() bool {
	if x != nil {
		return x.IsIncludedInNetWorth
	}
	return false
}

func (x *Liability) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *Liability) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *Liability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Liability) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Liability) GetFiles() []*FileInfo {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *Liability) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Liability) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateLiabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Creditor      string                 `protobuf:"bytes,3,opt,name=creditor,proto3" json:"creditor,omitempty"`
	Type          LiabilityType          `protobuf:"varint,4,opt,name=type,proto3,enum=asset.LiabilityType" json:"type,omitempty"`
	Principal     float64                `protobuf:"fixed64,5,opt,name=principal,proto3" json:"principal,omitempty"`
	InterestRate  float64                `protobuf:"fixed64,6,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	Description   string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	NewFiles      []*FileInfo            `protobuf:"bytes,10,rep,name=new_files,json=newFiles,proto3" json:"new_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLiabilityRequest) Reset() {
	*x = CreateLiabilityRequest{}
	mi := &file_proto_asset_liability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLiabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLiabilityRequest) ProtoMessage() {}

func (x *CreateLiabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_liability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLiabilityRequest.ProtoReflect.Descriptor instead.
func (*CreateLiabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_liability_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLiabilityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateLiabilityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLiabilityRequest) GetCreditor() string {
	if x != nil {
		return x.Creditor
	}
	return ""
}

func (x *CreateLiabilityRequest) GetType() LiabilityType {
	if x != nil {
		return x.Type
	}
	return LiabilityType_LIABILITY_TYPE_UNSPECIFIED
}

func (x *CreateLiabilityRequest) GetPrincipal() float64 {
	if x != nil {
		return x.Principal
	}
	return 0
}

func (x *CreateLiabilityRequest) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *CreateLiabilityRequest) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *CreateLiabilityRequest) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *CreateLiabilityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateLiabilityRequest) GetNewFiles() []*FileInfo {
	if x != nil {
		return x.NewFiles
	}
	return nil
}

type GetLiabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiabilityRequest) Reset() {
	*x = GetLiabilityRequest{}
	mi := &file_proto_asset_liability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiabilityRequest) ProtoMessage() {}

func (x *GetLiabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_liability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiabilityRequest.ProtoReflect.Descriptor instead.
func (*GetLiabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_liability_proto_rawDescGZIP(), []int{2}
}

func (x *GetLiabilityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetLiabilityByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLiabilityByIDRequest) Reset() {
	*x = GetLiabilityByIDRequest{}
	mi := &file_proto_asset_liability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLiabilityByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLiabilityByIDRequest) ProtoMessage() {}

func (x *GetLiabilityByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_liability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLiabilityByIDRequest.ProtoReflect.Descriptor instead.
func (*GetLiabilityByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_liability_proto_rawDescGZIP(), []int{3}
}

func (x *GetLiabilityByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetLiabilityByIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type UpdateLiabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Creditor      string                 `protobuf:"bytes,4,opt,name=creditor,proto3" json:"creditor,omitempty"`
	Type          LiabilityType          `protobuf:"varint,5,opt,name=type,proto3,enum=asset.LiabilityType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Principal     float64                `protobuf:"fixed64,7,opt,name=principal,proto3" json:"principal,omitempty"`
	InterestRate  float64                `protobuf:"fixed64,8,opt,name=interest_rate,json=interestRate,proto3" json:"interest_rate,omitempty"`
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`
	EndAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=end_at,json=endAt,proto3" json:"end_at,omitempty"`
	NewFiles      []*FileInfo            `protobuf:"bytes,11,rep,name=new_files,json=newFiles,proto3" json:"new_files,omitempty"`
	DeleteFileIds []string               `protobuf:"bytes,12,rep,name=delete_file_ids,json=deleteFileIds,proto3" json:"delete_file_ids,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,13,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLiabilityRequest) Reset() {
	*x = UpdateLiabilityRequest{}
	mi := &file_proto_asset_liability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLiabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLiabilityRequest) ProtoMessage() {}

func (x *UpdateLiabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_liability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLiabilityRequest.ProtoReflect.Descriptor instead.
func (*UpdateLiabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_liability_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateLiabilityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLiabilityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateLiabilityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateLiabilityRequest) GetCreditor() string {
	if x != nil {
		return x.Creditor
	}
	return ""
}

func (x *UpdateLiabilityRequest) GetType() LiabilityType {
	if x != nil {
		return x.Type
	}
	return LiabilityType_LIABILITY_TYPE_UNSPECIFIED
}

func (x *UpdateLiabilityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateLiabilityRequest) GetPrincipal() float64 {
	if x != nil {
		return x.Principal
	}
	return 0
}

func (x *UpdateLiabilityRequest) GetInterestRate() float64 {
	if x != nil {
		return x.InterestRate
	}
	return 0
}

func (x *UpdateLiabilityRequest) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *UpdateLiabilityRequest) GetEndAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndAt
	}
	return nil
}

func (x *UpdateLiabilityRequest) GetNewFiles() []*FileInfo {
	if x != nil {
		return x.NewFiles
	}
	return nil
}

func (x *UpdateLiabilityRequest) GetDeleteFileIds() []string {
	if x != nil {
		return x.DeleteFileIds
	}
	return nil
}

func (x *UpdateLiabilityRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type CreateLiabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLiabilityResponse) Reset() {
	*x = CreateLiabilityResponse{}
	mi := &file_proto_asset_liability_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLiabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLiabilityResponse) ProtoMessage() {}

func (x *CreateLiabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_liability_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLiabilityResponse.ProtoReflect.Descriptor instead.
func (*CreateLiabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_liability_proto_rawDescGZIP(), []int{5}
}

func (x *CreateLiabilityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateLiabilityResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LiabilityArrayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Liability     []*Liability           `protobuf:"bytes,2,rep,name=liability,proto3" json:"liability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiabilityArrayResponse) Reset() {
	*x = LiabilityArrayResponse{}
	mi := &file_proto_asset_liability_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiabilityArrayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiabilityArrayResponse) ProtoMessage() {}

func (x *LiabilityArrayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_liability_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiabilityArrayResponse.ProtoReflect.Descriptor instead.
func (*LiabilityArrayResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_liability_proto_rawDescGZIP(), []int{6}
}

func (x *LiabilityArrayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LiabilityArrayResponse) GetLiability() []*Liability {
	if x != nil {
		return x.Liability
	}
	return nil
}

type LiabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Liability     *Liability             `protobuf:"bytes,2,opt,name=liability,proto3" json:"liability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiabilityResponse) Reset() {
	*x = LiabilityResponse{}
	mi := &file_proto_asset_liability_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiabilityResponse) ProtoMessage() {}

func (x *LiabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_liability_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiabilityResponse.ProtoReflect.Descriptor instead.
func (*LiabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_liability_proto_rawDescGZIP(), []int{7}
}

func (x *LiabilityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LiabilityResponse) GetLiability() *Liability {
	if x != nil {
		return x.Liability
	}
	return nil
}

type DeleteLiabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLiabilityRequest) Reset() {
	*x = DeleteLiabilityRequest{}
	mi := &file_proto_asset_liability_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLiabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLiabilityRequest) ProtoMessage() {}

func (x *DeleteLiabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_liability_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLiabilityRequest.ProtoReflect.Descriptor instead.
func (*DeleteLiabilityRequest) Descriptor() ([]byte, []int) {
	return file_proto_asset_liability_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLiabilityRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteLiabilityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteLiabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLiabilityResponse) Reset() {
	*x = DeleteLiabilityResponse{}
	mi := &file_proto_asset_liability_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLiabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLiabilityResponse) ProtoMessage() {}

func (x *DeleteLiabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_asset_liability_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLiabilityResponse.ProtoReflect.Descriptor instead.
func (*DeleteLiabilityResponse) Descriptor() ([]byte, []int) {
	return file_proto_asset_liability_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLiabilityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_asset_liability_proto protoreflect.FileDescriptor

const file_proto_asset_liability_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/asset/liability.proto\x12\x05asset\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x16proto/asset/enum.proto\x1a\x16proto/asset/file.proto\"\xb8\x04\n" +
	"\tLiability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcreditor\x18\x03 \x01(\tR\bcreditor\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.asset.LiabilityTypeR\x04type\x12\x1c\n" +
	"\tprincipal\x18\x05 \x01(\x01R\tprincipal\x12#\n" +
	"\rinterest_rate\x18\x06 \x01(\x01R\finterestRate\x126\n" +
	"\x18is_included_in_net_worth\x18\a \x01(\bR\x14isIncludedInNetWorth\x125\n" +
	"\bstart_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x12 \n" +
	"\vdescription\x18\n" +
	" \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_by\x18\v \x01(\tR\tcreatedBy\x12%\n" +
	"\x05files\x18\f \x03(\v2\x0f.asset.FileInfoR\x05files\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x88\x03\n" +
	"\x16CreateLiabilityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bcreditor\x18\x03 \x01(\tR\bcreditor\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.asset.LiabilityTypeR\x04type\x12\x1c\n" +
	"\tprincipal\x18\x05 \x01(\x01R\tprincipal\x12#\n" +
	"\rinterest_rate\x18\x06 \x01(\x01R\finterestRate\x125\n" +
	"\bstart_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12,\n" +
	"\tnew_files\x18\n" +
	" \x03(\v2\x0f.asset.FileInfoR\bnewFiles\".\n" +
	"\x13GetLiabilityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"B\n" +
	"\x17GetLiabilityByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xfd\x03\n" +
	"\x16UpdateLiabilityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bcreditor\x18\x04 \x01(\tR\bcreditor\x12(\n" +
	"\x04type\x18\x05 \x01(\x0e2\x14.asset.LiabilityTypeR\x04type\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1c\n" +
	"\tprincipal\x18\a \x01(\x01R\tprincipal\x12#\n" +
	"\rinterest_rate\x18\b \x01(\x01R\finterestRate\x125\n" +
	"\bstart_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x121\n" +
	"\x06end_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x05endAt\x12,\n" +
	"\tnew_files\x18\v \x03(\v2\x0f.asset.FileInfoR\bnewFiles\x12&\n" +
	"\x0fdelete_file_ids\x18\f \x03(\tR\rdeleteFileIds\x12;\n" +
	"\vupdate_mask\x18\r \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"C\n" +
	"\x17CreateLiabilityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"b\n" +
	"\x16LiabilityArrayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\tliability\x18\x02 \x03(\v2\x10.asset.LiabilityR\tliability\"]\n" +
	"\x11LiabilityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\tliability\x18\x02 \x01(\v2\x10.asset.LiabilityR\tliability\"A\n" +
	"\x16DeleteLiabilityRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"3\n" +
	"\x17DeleteLiabilityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\x15Z\x13wealth-vault/pkg/pbb\x06proto3"

var (
	file_proto_asset_liability_proto_rawDescOnce sync.Once
	file_proto_asset_liability_proto_rawDescData []byte
)

func file_proto_asset_liability_proto_rawDescGZIP() []byte {
	file_proto_asset_liability_proto_rawDescOnce.Do(func() {
		file_proto_asset_liability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_asset_liability_proto_rawDesc), len(file_proto_asset_liability_proto_rawDesc)))
	})
	return file_proto_asset_liability_proto_rawDescData
}

var file_proto_asset_liability_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_asset_liability_proto_goTypes = []any{
	(*Liability)(nil),               // 0: asset.Liability
	(*CreateLiabilityRequest)(nil),  // 1: asset.CreateLiabilityRequest
	(*GetLiabilityRequest)(nil),     // 2: asset.GetLiabilityRequest
	(*GetLiabilityByIDRequest)(nil), // 3: asset.GetLiabilityByIDRequest
	(*UpdateLiabilityRequest)(nil),  // 4: asset.UpdateLiabilityRequest
	(*CreateLiabilityResponse)(nil), // 5: asset.CreateLiabilityResponse
	(*LiabilityArrayResponse)(nil),  // 6: asset.LiabilityArrayResponse
	(*LiabilityResponse)(nil),       // 7: asset.LiabilityResponse
	(*DeleteLiabilityRequest)(nil),  // 8: asset.DeleteLiabilityRequest
	(*DeleteLiabilityResponse)(nil), // 9: asset.DeleteLiabilityResponse
	(LiabilityType)(0),              // 10: asset.LiabilityType
	(*timestamppb.Timestamp)(nil),   // 11: google.protobuf.Timestamp
	(*FileInfo)(nil),                // 12: asset.FileInfo
	(*fieldmaskpb.FieldMask)(nil),   // 13: google.protobuf.FieldMask
}
var file_proto_asset_liability_proto_depIdxs = []int32{
	10, // 0: asset.Liability.type:type_name -> asset.LiabilityType
	11, // 1: asset.Liability.start_at:type_name -> google.protobuf.Timestamp
	11, // 2: asset.Liability.end_at:type_name -> google.protobuf.Timestamp
	12, // 3: asset.Liability.files:type_name -> asset.FileInfo
	11, // 4: asset.Liability.created_at:type_name -> google.protobuf.Timestamp
	11, // 5: asset.Liability.updated_at:type_name -> google.protobuf.Timestamp
	10, // 6: asset.CreateLiabilityRequest.type:type_name -> asset.LiabilityType
	11, // 7: asset.CreateLiabilityRequest.start_at:type_name -> google.protobuf.Timestamp
	11, // 8: asset.CreateLiabilityRequest.end_at:type_name -> google.protobuf.Timestamp
	12, // 9: asset.CreateLiabilityRequest.new_files:type_name -> asset.FileInfo
	10, // 10: asset.UpdateLiabilityRequest.type:type_name -> asset.LiabilityType
	11, // 11: asset.UpdateLiabilityRequest.start_at:type_name -> google.protobuf.Timestamp
	11, // 12: asset.UpdateLiabilityRequest.end_at:type_name -> google.protobuf.Timestamp
	12, // 13: asset.UpdateLiabilityRequest.new_files:type_name -> asset.FileInfo
	13, // 14: asset.UpdateLiabilityRequest.update_mask:type_name -> google.protobuf.FieldMask
	0,  // 15: asset.LiabilityArrayResponse.liability:type_name -> asset.Liability
	0,  // 16: asset.LiabilityResponse.liability:type_name -> asset.Liability
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_proto_asset_liability_proto_init() }
func file_proto_asset_liability_proto_init() {
	if File_proto_asset_liability_proto != nil {
		return
	}
	file_proto_asset_enum_proto_init()
	file_proto_asset_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_asset_liability_proto_rawDesc), len(file_proto_asset_liability_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_asset_liability_proto_goTypes,
		DependencyIndexes: file_proto_asset_liability_proto_depIdxs,
		MessageInfos:      file_proto_asset_liability_proto_msgTypes,
	}.Build()
	File_proto_asset_liability_proto = out.File
	file_proto_asset_liability_proto_goTypes = nil
	file_proto_asset_liability_proto_depIdxs = nil
}
