// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/user/user_request.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_user_user_request_proto protoreflect.FileDescriptor

const file_proto_user_user_request_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/user/user_request.proto\x12\x04user\x1a\x15proto/user/user.proto\x1a\x16proto/user/group.proto2\xb7\x04\n" +
	"\vUserService\x129\n" +
	"\n" +
	"CreateUser\x12\x17.user.CreateUserRequest\x1a\x12.user.UserResponse\x127\n" +
	"\aGetUser\x12\x18.user.GetUserByIDRequest\x1a\x12.user.UserResponse\x129\n" +
	"\n" +
	"UpdateUser\x12\x17.user.UpdateUserRequest\x1a\x12.user.UserResponse\x12C\n" +
	"\rGetFriendList\x12\x18.user.GetUserByIDRequest\x1a\x18.user.FriendListResponse\x126\n" +
	"\tAddFriend\x12\x13.user.FriendRequest\x1a\x14.user.FriendResponse\x12<\n" +
	"\vCreateGroup\x12\x18.user.CreateGroupRequest\x1a\x13.user.GroupResponse\x126\n" +
	"\bGetGroup\x12\x15.user.GetGroupRequest\x1a\x13.user.GroupResponse\x12H\n" +
	"\tGetMember\x12\x1c.user.GetGroupMembersRequest\x1a\x1d.user.GetGroupMembersResponse\x12<\n" +
	"\vUpdateGroup\x12\x18.user.UpdateGroupRequest\x1a\x13.user.GroupResponseB\x15Z\x13wealth-vault/pkg/pbb\x06proto3"

var file_proto_user_user_request_proto_goTypes = []any{
	(*CreateUserRequest)(nil),       // 0: user.CreateUserRequest
	(*GetUserByIDRequest)(nil),      // 1: user.GetUserByIDRequest
	(*UpdateUserRequest)(nil),       // 2: user.UpdateUserRequest
	(*FriendRequest)(nil),           // 3: user.FriendRequest
	(*CreateGroupRequest)(nil),      // 4: user.CreateGroupRequest
	(*GetGroupRequest)(nil),         // 5: user.GetGroupRequest
	(*GetGroupMembersRequest)(nil),  // 6: user.GetGroupMembersRequest
	(*UpdateGroupRequest)(nil),      // 7: user.UpdateGroupRequest
	(*UserResponse)(nil),            // 8: user.UserResponse
	(*FriendListResponse)(nil),      // 9: user.FriendListResponse
	(*FriendResponse)(nil),          // 10: user.FriendResponse
	(*GroupResponse)(nil),           // 11: user.GroupResponse
	(*GetGroupMembersResponse)(nil), // 12: user.GetGroupMembersResponse
}
var file_proto_user_user_request_proto_depIdxs = []int32{
	0,  // 0: user.UserService.CreateUser:input_type -> user.CreateUserRequest
	1,  // 1: user.UserService.GetUser:input_type -> user.GetUserByIDRequest
	2,  // 2: user.UserService.UpdateUser:input_type -> user.UpdateUserRequest
	1,  // 3: user.UserService.GetFriendList:input_type -> user.GetUserByIDRequest
	3,  // 4: user.UserService.AddFriend:input_type -> user.FriendRequest
	4,  // 5: user.UserService.CreateGroup:input_type -> user.CreateGroupRequest
	5,  // 6: user.UserService.GetGroup:input_type -> user.GetGroupRequest
	6,  // 7: user.UserService.GetMember:input_type -> user.GetGroupMembersRequest
	7,  // 8: user.UserService.UpdateGroup:input_type -> user.UpdateGroupRequest
	8,  // 9: user.UserService.CreateUser:output_type -> user.UserResponse
	8,  // 10: user.UserService.GetUser:output_type -> user.UserResponse
	8,  // 11: user.UserService.UpdateUser:output_type -> user.UserResponse
	9,  // 12: user.UserService.GetFriendList:output_type -> user.FriendListResponse
	10, // 13: user.UserService.AddFriend:output_type -> user.FriendResponse
	11, // 14: user.UserService.CreateGroup:output_type -> user.GroupResponse
	11, // 15: user.UserService.GetGroup:output_type -> user.GroupResponse
	12, // 16: user.UserService.GetMember:output_type -> user.GetGroupMembersResponse
	11, // 17: user.UserService.UpdateGroup:output_type -> user.GroupResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_user_request_proto_init() }
func file_proto_user_user_request_proto_init() {
	if File_proto_user_user_request_proto != nil {
		return
	}
	file_proto_user_user_proto_init()
	file_proto_user_group_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_user_request_proto_rawDesc), len(file_proto_user_user_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_user_request_proto_goTypes,
		DependencyIndexes: file_proto_user_user_request_proto_depIdxs,
	}.Build()
	File_proto_user_user_request_proto = out.File
	file_proto_user_user_request_proto_goTypes = nil
	file_proto_user_user_request_proto_depIdxs = nil
}
