# ---------- Build Stage ----------
FROM golang:1.25-bookworm AS builder

WORKDIR /app

COPY proto/ ./proto/
COPY services/auth-service/go.mod services/auth-service/go.sum ./services/auth-service/

WORKDIR /app/services/auth-service
RUN go mod download

WORKDIR /app
COPY services/auth-service/ ./services/auth-service/

WORKDIR /app/services/auth-service
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /app/auth-service ./cmd/main.go

# ---------- Runtime Stage ----------
FROM gcr.io/distroless/base-debian12

WORKDIR /app

ENV DB_HOST=postgres
ENV DB_PORT=5432
ENV DB_USER=admin
ENV DB_NAME=auth_db
ENV SSL_MODE=disable
ENV GRPC_PORT=50052

COPY --from=builder /app/auth-service /app/auth-service

EXPOSE 50052

CMD ["/app/auth-service"]