syntax = "proto3";

package user;

option go_package = "wealth-vault/pkg/pb";

import "google/protobuf/timestamp.proto";
import "google/protobuf/field_mask.proto";

message User {
  string id = 1;
  string email = 2;
  string firstname = 3;
  string lastname = 4;
  string username = 5;
  string profile = 6;
  string phonenumber = 7;
  google.protobuf.Timestamp birthday = 8;
  google.protobuf.Timestamp created_at = 9;
  google.protobuf.Timestamp updated_at = 10;
}

message CreateUserRequest {
  string email = 1;
  string username = 2;
}

message GetUserByIDRequest {
  string id = 1;
}

message UpdateUserRequest {
  string id = 1;          
  string firstname = 2;
  string lastname = 3;
  string username = 4;
  string profile = 5;
  string phonenumber = 6;
  google.protobuf.Timestamp birthday = 7;
  google.protobuf.FieldMask update_mask = 8;   
}

message UserResponse {
  bool success = 1;
  User user = 2;
}

message FriendRequest {
  string id = 1; 
  string user_id = 2;
}

message FriendResponse {
  bool success = 1;
}

message FriendListResponse {
  bool success = 1;
  User user = 2;
  repeated User friends = 3;
}