syntax = "proto3";

package user;

option go_package = "wealth-vault/pkg/pb";

import "google/protobuf/timestamp.proto";
import "google/protobuf/field_mask.proto";

message User {
  string id = 1;
  string email = 2;
  string firstname = 3;
  string lastname = 4;
  string username = 5;
  string profile = 6;
  string phonenumber = 7;
  google.protobuf.Timestamp birthday = 8;
  int32 sharedage = 9 ;
  bool sharedenabled = 10;
  google.protobuf.Timestamp created_at = 11;
  google.protobuf.Timestamp updated_at = 12;
  bool is_friend = 13;
  bool is_close_friend = 14;
}

message CreateUserRequest {
  string email = 1;
  string username = 2;
}

message GetUserByIDRequest {
  string id = 1;
}

message GetUserByEmailRequest {
  string email = 1;
  string id = 2;
}

message UpdateUserRequest {
  string id = 1;          
  string firstname = 2;
  string lastname = 3;
  string username = 4;
  string profile = 5;
  string phonenumber = 6;
  google.protobuf.Timestamp birthday = 7;
  optional int32 sharedage = 8;   
  optional bool sharedenabled = 9;
  google.protobuf.FieldMask update_mask = 10;   
}

message UserResponse {
  bool success = 1;
  User user = 2;
}

message UserInfoResponse {
  bool success = 1;
  repeated User user = 2;
}

message FriendRequest {
  string id = 1; 
  string user_id = 2;
}

message AcceptFriendRequest {
  string user_id = 1;      
  string requester_id = 2; 
  string action = 3;   
}

message FriendResponse {
  bool success = 1;
}

message FriendListResponse {
  repeated User friends = 1;
}

message SetCloseFriendRequest {
  string user_id = 1;   
  string friend_id = 2;
  bool is_close = 3;    
}

message SetCloseFriendResponse {
  bool success = 1;
}

message GetCloseFriendsRequest {
  string user_id = 1;
}

message GetCloseFriendsResponse {
  repeated User friends  = 1;
}

message CheckFriendshipRequest {
  string user_id = 1;
  string target_id = 2;
}

message CheckFriendshipResponse {
  bool is_friend = 1;
}